CREATE USER logic_u1 IDENTIFIED by Cantian123;
GRANT CREATE SESSION TO logic_u1 WITH ADMIN OPTION;
GRANT CREATE TABLE TO logic_u1;
GRANT DBA TO logic_u1;
COMMIT;

conn logic_u1/Cantian123@127.0.0.1:1611
ALTER DATABASE ENABLE_LOGIC_REPLICATION ON;
CREATE TABLE logic_t1 (id int primary key);
ALTER TABLE logic_t1 ADD LOGICAL LOG(PRIMARY KEY);
INSERT INTO logic_t1 VALUES(1);
DELETE logic_t1 WHERE id=1;
COMMIT;
