DROP TABLE IF EXISTS T_MULTI_DEL;
DROP TABLE IF EXISTS T_MULTI_DEL_TRIG;
CREATE TABLE T_MULTI_DEL(F1 INT, F2 INT);
CREATE TABLE T_MULTI_DEL_TRIG(F1 INT, F2 INT);
CREATE INDEX IDX_T_MULTI_DEL ON T_MULTI_DEL(F1);
INSERT INTO T_MULTI_DEL VALUES(1,1);

CREATE OR REPLACE TRIGGER MULTI_DEL_TRIG_ROW BEFORE DELETE ON T_MULTI_DEL
FOR EACH ROW
BEGIN
  INSERT INTO T_MULTI_DEL_TRIG VALUES(1,1);
END;
/

DELETE T1,T2 FROM T_MULTI_DEL T1 JOIN T_MULTI_DEL T2 ON T1.F1=T2.F1;
SELECT COUNT(*) FROM T_MULTI_DEL_TRIG;
ROLLBACK;
DROP TABLE IF EXISTS T_MULTI_DEL;
DROP TABLE IF EXISTS T_MULTI_DEL_TRIG;

DROP TABLE IF EXISTS T_MULTI_DEL_MIGR;
DROP TABLE IF EXISTS T_MULTI_DEL_TRIG_MIGR;
CREATE TABLE T_MULTI_DEL_MIGR(F1 INT, F2 VARCHAR(4000), F3 VARCHAR(4000));
CREATE TABLE T_MULTI_DEL_TRIG_MIGR(F1 INT, F2 VARCHAR(4000), F3 VARCHAR(4000));
CREATE INDEX IDX_T_MULTI_DEL_MIGR ON T_MULTI_DEL_MIGR(F1);
INSERT INTO T_MULTI_DEL_MIGR VALUES(1,'a',lpad('a',3500,'a'));
INSERT INTO T_MULTI_DEL_MIGR VALUES(2,'b',lpad('b',3500,'b'));
UPDATE T_MULTI_DEL_MIGR SET F2=lpad('c',4000,'c'),F3=lpad('d',4000,'d');

CREATE OR REPLACE TRIGGER MULTI_DEL_TRIG_ROW_MIGR BEFORE DELETE ON T_MULTI_DEL_MIGR
FOR EACH ROW
BEGIN
  INSERT INTO T_MULTI_DEL_TRIG_MIGR VALUES(1,'a',lpad('a',3500,'a'));
  INSERT INTO T_MULTI_DEL_TRIG_MIGR VALUES(2,'b',lpad('b',3500,'b'));
  UPDATE T_MULTI_DEL_TRIG_MIGR SET F2=lpad('c',4000,'c'),F3=lpad('d',4000,'d');
END;
/

DELETE T1,T2 FROM T_MULTI_DEL_MIGR T1 JOIN T_MULTI_DEL_MIGR T2 ON T1.F1=T2.F1;
SELECT COUNT(*) FROM T_MULTI_DEL_TRIG_MIGR;
ROLLBACK;
DROP TABLE IF EXISTS T_MULTI_DEL_MIGR;
DROP TABLE IF EXISTS T_MULTI_DEL_TRIG_MIGR;


DROP TABLE IF EXISTS T_MULTI_DEL_LINK;
DROP TABLE IF EXISTS T_MULTI_DEL_TRIG_LINK;
CREATE TABLE T_MULTI_DEL_LINK(F1 INT, F2 VARCHAR(8000),F3 VARCHAR(8000),F4 VARCHAR(8000),F5 VARCHAR(8000));
CREATE TABLE T_MULTI_DEL_TRIG_LINK(F1 INT, F2 VARCHAR(8000),F3 VARCHAR(8000),F4 VARCHAR(8000),F5 VARCHAR(8000));
CREATE INDEX IDX_T_MULTI_DEL_LINK ON T_MULTI_DEL_LINK(F1);
INSERT INTO T_MULTI_DEL_LINK VALUES(1,LPAD('A',8000,'A'),LPAD('B',8000,'B'),LPAD('C',8000,'C'),'D');

CREATE OR REPLACE TRIGGER MULTI_DEL_TRIG_ROW_LINK BEFORE DELETE ON T_MULTI_DEL_LINK
FOR EACH ROW
BEGIN
  INSERT INTO T_MULTI_DEL_TRIG_LINK VALUES(1,LPAD('A',8000,'A'),LPAD('B',8000,'B'),LPAD('C',8000,'C'),'D');
END;
/

DELETE T1,T2 FROM T_MULTI_DEL_LINK T1 JOIN T_MULTI_DEL_LINK T2 ON T1.F1=T2.F1;
SELECT COUNT(*) FROM T_MULTI_DEL_TRIG_LINK;
ROLLBACK;
DROP TABLE IF EXISTS T_MULTI_DEL_LINK;
DROP TABLE IF EXISTS T_MULTI_DEL_TRIG_LINK;
