CONN / AS SYSDBA
DROP USER IF EXISTS PL_DC3 CASCADE;
CREATE USER PL_DC3 IDENTIFIED BY Cantian_123456;
GRANT DBA TO PL_DC3;
GRANT EXECUTE ON DBE_DIAGNOSE TO PL_DC3;
conn PL_DC3/Cantian_123456@127.0.0.1:1611
SET SERVEROUTPUT ON

CREATE OR REPLACE PACKAGE PKG1 IS
 FUNCTION F1(C1 INT) RETURN INT;
 PROCEDURE P1(C1 INT);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG1 IS
 FUNCTION F1(C1 INT) RETURN INT IS
 BEGIN
  P1(C1);
  RETURN C1;
 END;
 PROCEDURE P1(C1 INT) IS
 BEGIN
  dbe_output.print_line('I AM PL_DC3.PKG1');
 END;
END;
/

SELECT PL_DC3.PKG1.F1(1);
CALL PL_DC3.PKG1.P1(1);

CALL PL_DC3.PKG1.F1(1);
SELECT PL_DC3.PKG1.P1(1);

CREATE OR REPLACE SYNONYM PKG1 FOR PKG1;--ERROR
CREATE OR REPLACE SYNONYM PKG2 FOR PKG1;

SELECT PL_DC3.PKG2.F1(1);
CALL PL_DC3.PKG2.P1(1);

CALL PL_DC3.PKG2.F1(1);
SELECT PL_DC3.PKG2.P1(1);

CONN / AS SYSDBA
DROP USER IF EXISTS PL_DC3 CASCADE;




