-- set _log_level to 0x00000007
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x00000017
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 23;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x0000001F
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 31;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x00000097
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 151;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x0000009F
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 159;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x00000037
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 55;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x0000003F
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 63;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x000000B7
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 183;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x000000BF
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 191;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x000000FF
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 255;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x00000077
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 119;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x000000F7
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 247;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level to 0x0000007F
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 127;
SHOW PARAMETER _LOG_LEVEL;



-- set _log_level_mode to RUN
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL_MODE = RUN;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level_mode to ERROR
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL_MODE = ERROR;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level_mode to WARN
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL_MODE = WARN;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level_mode to DEBUG
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL_MODE = DEBUG;
SHOW PARAMETER _LOG_LEVEL;


-- set _log_level_mode to FATAL
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL_MODE = FATAL;
SHOW PARAMETER _LOG_LEVEL;


-- set LONGSQL_LOG_MODE to ON
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET LONGSQL_LOG_MODE = ON;
SHOW PARAMETER _LOG_LEVEL;


-- set LONGSQL_LOG_MODE to OFF
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET LONGSQL_LOG_MODE = OFF;
SHOW PARAMETER _LOG_LEVEL;


-- set _LOG_LEVEL_MODE to USER_DEFINE
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL_MODE = USER_DEFINE;
SHOW PARAMETER _LOG_LEVEL;


-- set _LOG_LEVEL to 17
ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;
ALTER SYSTEM SET _LOG_LEVEL = 17;
SHOW PARAMETER _LOG_LEVEL;


ALTER SYSTEM SET _LOG_LEVEL = 7;
SHOW PARAMETER _LOG_LEVEL;

--DTS2019122710305
alter system set audit_level="001";
show parameter audit_level;
alter system set audit_level="+100";
show parameter audit_level;
alter system set audit_level="256";
alter system set audit_level=003;
show parameter audit_level;

--SHOW PARAMETER NOT EXISTS
show parameter abcdefghit