CONN / AS SYSDBA
ALTER SYSTEM SET LOCAL_TEMPORARY_TABLE_ENABLED=TRUE;

DROP USER IF EXISTS USER_CACHE_TEST CASCADE;
CREATE USER USER_CACHE_TEST IDENTIFIED BY Cantian_234;
GRANT DBA TO USER_CACHE_TEST;

CONN USER_CACHE_TEST/Cantian_234@127.0.0.1:1611
CREATE TEMPORARY TABLE #USER_CACHE_TEST_T1(C1 INT);
CREATE TABLE USER_CACHE_TEST_T1(C1 INT);
INSERT INTO #USER_CACHE_TEST_T1 VALUES(1);
INSERT INTO USER_CACHE_TEST_T1 VALUES(1);
COMMIT;

SELECT SQL_TEXT, EXECUTIONS, REF_COUNT FROM DV_SQLS WHERE SQL_TEXT LIKE '%USER_CACHE_TEST_T1%' ORDER BY SQL_TEXT;

BEGIN
 INSERT INTO #USER_CACHE_TEST_T1 VALUES(2);
 COMMIT;
END;
/
BEGIN
 INSERT INTO USER_CACHE_TEST_T1 VALUES(2);
 COMMIT;
END;
/

SELECT SQL_TEXT, EXECUTIONS, REF_COUNT FROM dv_anonymous WHERE SQL_TEXT LIKE '%USER_CACHE_TEST_T1%' ORDER BY SQL_TEXT;

CREATE OR REPLACE PROCEDURE USER_CACHE_TEST_P1(C1 INT) IS
BEGIN
 INSERT INTO #USER_CACHE_TEST_T1 VALUES(C1);
 COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE USER_CACHE_TEST_P2(C1 INT) IS
BEGIN
 INSERT INTO USER_CACHE_TEST_T1 VALUES(C1);
 COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE USER_CACHE_TEST_P3(C1 INT) IS
BEGIN
 FOR ITEM IN (SELECT * FROM #USER_CACHE_TEST_T1) LOOP
   NULL;
 END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE USER_CACHE_TEST_P4(C1 INT) IS
BEGIN
  FOR ITEM IN (SELECT * FROM USER_CACHE_TEST_T1) LOOP
   NULL;
 END LOOP;
END;
/

CALL USER_CACHE_TEST_P1(3);
CALL USER_CACHE_TEST_P2(3);
CALL USER_CACHE_TEST_P3(3);
CALL USER_CACHE_TEST_P4(3);

SELECT NAME FROM DV_PL_ENTITY WHERE USER_NAME='USER_CACHE_TEST' ORDER BY NAME;
SELECT SQL_TEXT, EXECUTIONS, REF_COUNT FROM dv_anonymous WHERE SQL_TEXT LIKE '%USER_CACHE_TEST_P%' ORDER BY SQL_TEXT;

CREATE OR REPLACE FUNCTION USER_CACHE_TEST_F1(C1 INT) RETURN INT IS
BEGIN
 INSERT INTO #USER_CACHE_TEST_T1 VALUES(C1);
 RETURN 1;
END;
/

CREATE OR REPLACE FUNCTION USER_CACHE_TEST_F2(C1 INT) RETURN INT IS
BEGIN
 INSERT INTO USER_CACHE_TEST_T1 VALUES(C1);
 RETURN 1;
END;
/

CREATE OR REPLACE FUNCTION USER_CACHE_TEST_F3(C1 INT) RETURN INT IS
BEGIN
 FOR ITEM IN (SELECT * FROM #USER_CACHE_TEST_T1) LOOP
   NULL;
 END LOOP;
 RETURN 1;
END;
/

CREATE OR REPLACE FUNCTION USER_CACHE_TEST_F4(C1 INT) RETURN INT IS
BEGIN
  FOR ITEM IN (SELECT * FROM USER_CACHE_TEST_T1) LOOP
   NULL;
 END LOOP;
 RETURN 1;
END;
/

CALL USER_CACHE_TEST_P1(3);
CALL USER_CACHE_TEST_P2(3);
CALL USER_CACHE_TEST_P3(3);
CALL USER_CACHE_TEST_P4(3);

SELECT USER_CACHE_TEST_F1(1);
SELECT USER_CACHE_TEST_F2(1);
SELECT USER_CACHE_TEST_F3(1);
SELECT USER_CACHE_TEST_F4(1);

SELECT NAME FROM DV_PL_ENTITY WHERE USER_NAME='USER_CACHE_TEST' ORDER BY NAME;
SELECT SQL_TEXT, EXECUTIONS, REF_COUNT FROM DV_SQLS WHERE SQL_TEXT LIKE '%USER_CACHE_TEST_F%' ORDER BY SQL_TEXT;

SELECT USER_CACHE_TEST_F1(1);
SELECT USER_CACHE_TEST_F2(1);
SELECT USER_CACHE_TEST_F3(1);
SELECT USER_CACHE_TEST_F4(1);

CONN / AS SYSDBA
DROP USER IF EXISTS USER_CACHE_TEST CASCADE;
