drop table if exists abc;
create table abc(abort int);
select abort from abc;
drop table abc;
create table abc(account int);
select account from abc;
drop table abc;
create table abc(activate int);
select activate from abc;
drop table abc;
create table abc(active int);
select active from abc;
drop table abc;
create table abc(appendonly int);
select appendonly from abc;
drop table abc;
create table abc(archivelog int);
select archivelog from abc;
drop table abc;
create table abc(async int);
select async from abc;
drop table abc;
create table abc(autoextend int);
select autoextend from abc;
drop table abc;
create table abc(automatic int);
select automatic from abc;
drop table abc;
create table abc(autonomous_transaction int);
select autonomous_transaction from abc;
drop table abc;
create table abc(autopurge int);
select autopurge from abc;
drop table abc;
create table abc(availability int);
select availability from abc;
drop table abc;
create table abc(backup int);
select backup from abc;
drop table abc;
create table abc(build int);
select build from abc;
drop table abc;
create table abc(cache int);
select cache from abc;
drop table abc;
create table abc(cancel int);
select cancel from abc;
drop table abc;
create table abc(cascade int);
select cascade from abc;
drop table abc;
create table abc(case int);
select case from abc;
create table abc(cast int);
select cast from abc;
drop table abc;
create table abc(catalog int);
select catalog from abc;
drop table abc;
create table abc(character int);
select character from abc;
drop table abc;
create table abc(check int);
select check from abc;
drop table abc;
create table abc(checkpoint int);
select checkpoint from abc;
drop table abc;
create table abc(comment int);
select comment from abc;
drop table abc;
create table abc(commit int);
select commit from abc;
drop table abc;
create table abc(config int);
select config from abc;
drop table abc;
create table abc(consistency int);
select consistency from abc;
drop table abc;
create table abc(controlfile int);
select controlfile from abc;
drop table abc;
create table abc(convert int);
select convert from abc;
drop table abc;
create table abc(currval int);
select currval from abc;
drop table abc;
create table abc(cursor int);
select cursor from abc;
drop table abc;
create table abc(cycle int);
select cycle from abc;
drop table abc;
create table abc(database int);
select database from abc;
drop table abc;
create table abc(datafile int);
select datafile from abc;
drop table abc;
create table abc(declare int);
select declare from abc;
drop table abc;
create table abc(dictionary int);
select dictionary from abc;
drop table abc;
create table abc(disable int);
select disable from abc;
drop table abc;
create table abc(discard int);
select discard from abc;
drop table abc;
create table abc(disconnect int);
select disconnect from abc;
drop table abc;
create table abc(distribute int);
select distribute from abc;
drop table abc;
create table abc(do int);
select do from abc;
drop table abc;
create table abc(dump int);
select dump from abc;
drop table abc;
create table abc(duplicate int);
select duplicate from abc;
drop table abc;
create table abc(enable int);
select enable from abc;
drop table abc;
create table abc(end int);
select end from abc;
drop table abc;
create table abc(error int);
select error from abc;
drop table abc;
create table abc(exception int);
select exception from abc;
drop table abc;
create table abc(execute int);
select execute from abc;
drop table abc;
create table abc(explain int);
select explain from abc;
drop table abc;
create table abc(failover int);
select failover from abc;
drop table abc;
create table abc(fetch int);
select fetch from abc;
drop table abc;
create table abc(flashback int);
select flashback from abc;
drop table abc;
create table abc(force int);
select force from abc;
drop table abc;
create table abc(foreign int);
select foreign from abc;
drop table abc;
create table abc(format int);
select format from abc;
drop table abc;
create table abc(full int);
select full from abc;
drop table abc;
create table abc(function int);
select function from abc;
drop table abc;
create table abc(global int);
select global from abc;
drop table abc;
create table abc(goto int);
select goto from abc;
drop table abc;
create table abc(hash int);
select hash from abc;
drop table abc;
create table abc(if int);
select if from abc;
drop table abc;
create table abc(including int);
select including from abc;
drop table abc;
create table abc(incremental int);
select incremental from abc;
drop table abc;
create table abc(index_asc int);
select index_asc from abc;
drop table abc;
create table abc(index_desc int);
select index_desc from abc;
drop table abc;
create table abc(initrans int);
select initrans from abc;
drop table abc;
create table abc(inner int);
select inner from abc;
drop table abc;
create table abc(instance int);
select instance from abc;
drop table abc;
create table abc(isnot int);
select isnot from abc;
drop table abc;
create table abc(join int);
select join from abc;
drop table abc;
create table abc(keep int);
select keep from abc;
drop table abc;
create table abc(key int);
select key from abc;
drop table abc;
create table abc(kill int);
select kill from abc;
drop table abc;
create table abc(left int);
select left from abc;
drop table abc;
create table abc(less int);
select less from abc;
drop table abc;
create table limit(limit int);
insert into limit(limit) values(1),(2),(3);
select limit limit from limit limit order by limit limit 1;
update limit set limit = limit + 1;
delete from limit limit 1;
delete from limit where limit < 1;
drop table limit;
create table abc(load int);
select load from abc;
drop table abc;
create table abc(lob int);
select lob from abc;
drop table abc;
create table abc(local int);
select local from abc;
drop table abc;
create table abc(lock_wait int);
select lock_wait from abc;
drop table abc;
create table abc(logfile int);
select logfile from abc;
drop table abc;
create table abc(loop int);
select loop from abc;
drop table abc;
create table abc(managed int);
select managed from abc;
drop table abc;
create table abc(maximize int);
select maximize from abc;
drop table abc;
create table abc(maxtrans int);
select maxtrans from abc;
drop table abc;
create table abc(maxvalue int);
select maxvalue from abc;
drop table abc;
create table abc(member int);
select member from abc;
drop table abc;
create table abc(memory int);
select memory from abc;
drop table abc;
create table abc(merge int);
select merge from abc;
drop table abc;
create table abc(minvalue int);
select minvalue from abc;
drop table abc;
create table abc(mode int);
select mode from abc;
drop table abc;
create table abc(monitor int);
select monitor from abc;
drop table abc;
create table abc(mount int);
select mount from abc;
drop table abc;
create table abc(move int);
select move from abc;
drop table abc;
create table abc(nextval int);
select nextval from abc;
drop table abc;
create table abc(noarchivelog int);
select noarchivelog from abc;
drop table abc;
create table abc(nocache int);
select nocache from abc;
drop table abc;
create table abc(nocycle int);
select nocycle from abc;
drop table abc;
create table abc(node int);
select node from abc;
drop table abc;
create table abc(nologging int);
select nologging from abc;
drop table abc;
create table abc(nomaxvalue int);
select nomaxvalue from abc;
drop table abc;
create table abc(nominvalue int);
select nominvalue from abc;
drop table abc;
create table abc(noorder int);
select noorder from abc;
drop table abc;
create table abc(off int);
select off from abc;
drop table abc;
create table abc(offset int);
select offset from abc;
drop table abc;
create table abc(only int);
select only from abc;
drop table abc;
create table abc(open int);
select open from abc;
drop table abc;
create table abc(organization int);
select organization from abc;
drop table abc;
create table abc(outer int);
select outer from abc;
drop table abc;
create table abc(parameter int);
select parameter from abc;
drop table abc;
create table abc(partition int);
select partition from abc;
drop table abc;
create table abc(password int);
select password from abc;
drop table abc;
create table abc(path int);
select path from abc;
drop table abc;
create table abc(pctfree int);
select pctfree from abc;
drop table abc;
create table abc(performance int);
select performance from abc;
drop table abc;
create table abc(physical int);
select physical from abc;
drop table abc;
create table abc(plan int);
select plan from abc;
drop table abc;
create table abc(prepare int);
select prepare from abc;
drop table abc;
create table abc(prepared int);
select prepared from abc;
drop table abc;
create table abc(preserve int);
select preserve from abc;
drop table abc;
create table abc(primary int);
select primary from abc;
drop table abc;
create table abc(procedure int);
select procedure from abc;
drop table abc;
create table abc(protection int);
select protection from abc;
drop table abc;
create table abc(protection int);
select protection from abc;
drop table abc;
create table abc(purge int);
select purge from abc;
drop table abc;
create table abc(raise int);
select raise from abc;
drop table abc;
create table abc(range int);
select range from abc;
drop table abc;
create table abc(read int);
select read from abc;
drop table abc;
create table abc(readonly int);
select readonly from abc;
drop table abc;
create table abc(readwrite int);
select readwrite from abc;
drop table abc;
create table abc(rebuild int);
select rebuild from abc;
drop table abc;
create table abc(recover int);
select recover from abc;
drop table abc;
create table abc(recyclebin int);
select recyclebin from abc;
drop table abc;
create table abc(redo int);
select redo from abc;
drop table abc;
create table abc(references int);
select references from abc;
drop table abc;
create table abc(register int);
select register from abc;
drop table abc;
create table abc(release int);
select release from abc;
drop table abc;
create table abc(replace int);
select replace from abc;
drop table abc;
create table abc(reset int);
select reset from abc;
drop table abc;
create table abc(resize int);
select resize from abc;
drop table abc;
create table abc(restore int);
select restore from abc;
drop table abc;
create table abc(reuse int);
select reuse from abc;
drop table abc;
create table abc(right int);
select right from abc;
drop table abc;
create table abc(rollback int);
select rollback from abc;
drop table abc;
create table abc(savepoint int);
select savepoint from abc;
drop table abc;
create table abc(scn int);
select scn from abc;
drop table abc;
create table abc(secondary int);
select secondary from abc;
drop table abc;
create table abc(separator int);
select separator from abc;
drop table abc;
create table abc(sequence int);
select sequence from abc;
drop table abc;
create table abc(serializable int);
select serializable from abc;
drop table abc;
create table abc(server int);
select server from abc;
drop table abc;
create table abc(share int);
select share from abc;
drop table abc;
create table abc(show int);
select show from abc;
drop table abc;
create table abc(shutdown int);
select shutdown from abc;
drop table abc;
create table abc(signal int);
select signal from abc;
drop table abc;
create table abc(size int);
select size from abc;
drop table abc;
create table abc(split_factor int);
select split_factor from abc;
drop table abc;
create table abc(standard int);
select standard from abc;
drop table abc;
create table abc(standby int);
select standby from abc;
drop table abc;
create table abc(startup int);
select startup from abc;
drop table abc;
create table abc(stop int);
select stop from abc;
drop table abc;
create table abc(storage int);
select storage from abc;
drop table abc;
create table abc(switch int);
select switch from abc;
drop table abc;
create table abc(switchover int);
select switchover from abc;
drop table abc;
create table abc(syncpoint int);
select syncpoint from abc;
drop table abc;
create table abc(system int);
select system from abc;
drop table abc;
create table abc(tablespace int);
select tablespace from abc;
drop table abc;
create table abc(temp int);
select temp from abc;
drop table abc;
create table abc(tempfile int);
select tempfile from abc;
drop table abc;
create table abc(temporary int);
select temporary from abc;
drop table abc;
create table abc(than int);
select than from abc;
drop table abc;
create table abc(thread int);
select thread from abc;
drop table abc;
create table abc(timeout int);
select timeout from abc;
drop table abc;
create table abc(transaction int);
select transaction from abc;
drop table abc;
create table abc(truncate int);
select truncate from abc;
drop table abc;
create table abc(undo int);
select undo from abc;
drop table abc;
create table abc(unique int);
select unique from abc;
drop table abc;
create table abc(unlock int);
select unlock from abc;
drop table abc;
create table abc(using int);
select using from abc;
drop table abc;
create table abc(value int);
select value from abc;
drop table abc;
create table abc(wait int);
select wait from abc;
drop table abc;
create table abc(when int);
select when from abc;
drop table abc;
create table abc(bigint int);
select bigint from abc;
drop table abc;
create table abc(binary int);
select binary from abc;
drop table abc;
create table abc(blob int);
select blob from abc;
drop table abc;
create table abc(bool int);
select bool from abc;
drop table abc;
create table abc(bytea int);
select bytea from abc;
drop table abc;
create table abc(clob int);
select clob from abc;
drop table abc;
create table abc(datetime int);
select datetime from abc;
drop table abc;
create table abc(double int);
select double from abc;
drop table abc;
create table abc(float int);
select float from abc;
drop table abc;
create table abc(int int);
select int from abc;
drop table abc;
create table abc(interval int);
select interval from abc;
drop table abc;
create table abc(numeric int);
select numeric from abc;
drop table abc;
create table abc(real int);
select real from abc;
drop table abc;
create table abc(serial int);
select serial from abc;
drop table abc;
create table abc(text int);
select text from abc;
drop table abc;
create table abc(timestamp int);
select timestamp from abc;
drop table abc;
create table abc(varbinary int);
select varbinary from abc;
drop table abc;
create table abc(connect_by_iscycle int);
select connect_by_iscycle from abc;
drop table abc;
create table abc(connect_by_isleaf int);
select connect_by_isleaf from abc;
drop table abc;
create table abc(ctid int);
select ctid from abc;
drop table abc;
create table abc(curdate int);
select curdate from abc;
drop table abc;
create table abc(current_date int);
select current_date from abc;
drop table abc;
create table abc(current_timestamp int);
select current_timestamp from abc;
drop table abc;
create table abc(false int);
select false from abc;
drop table abc;
create table abc(systimestamp int);
select systimestamp from abc;
drop table abc;
create table abc(true int);
select true from abc;
drop table abc;
create table abc(xc_node_id int);
select xc_node_id from abc;
drop table abc;

--not namable
drop table if exists abc;
create table abc(add  int);
 drop table abc;
create table abc(all  int);
 drop table abc;
create table abc(alter  int);
 drop table abc;
create table abc(and  int);
 drop table abc;
create table abc(any  int);
 drop table abc;
create table abc(as  int);
 drop table abc;
create table abc(asc  int);
 drop table abc;
create table abc(audit  int);
 drop table abc;
create table abc(begin  int);
 drop table abc;
create table abc(between  int);
 drop table abc;
create table abc(by  int);
 drop table abc;
create table abc(column  int);
 drop table abc;
create table abc(compress  int);
 drop table abc;
create table abc(connect  int);
 drop table abc;
create table abc(constraint  int);
 drop table abc;
create table abc(create  int);
 drop table abc;
create table abc(current  int);
 drop table abc;
create table abc(delete  int);
 drop table abc;
create table abc(desc  int);
 drop table abc;
create table abc(distinct  int);
 drop table abc;
create table abc(drop  int);
 drop table abc;
create table abc(else  int);
 drop table abc;
create table abc(exists  int);
 drop table abc;
create table abc(for  int);
 drop table abc;
create table abc(from  int);
 drop table abc;
create table abc(group  int);
 drop table abc;
create table abc(having  int);
 drop table abc;
create table abc(identified  int);
 drop table abc;
create table abc(in  int);
 drop table abc;
create table abc(increment  int);
 drop table abc;
create table abc(index  int);
 drop table abc;
create table abc(insert  int);
 drop table abc;
create table abc(intersect  int);
 drop table abc;
create table abc(into  int);
 drop table abc;
create table abc(is  int);
 drop table abc;
create table abc(level  int);
 drop table abc;
create table abc(like  int);
 drop table abc;
create table abc(lock  int);
 drop table abc;
create table abc(minus  int);
 drop table abc;
create table abc(modify  int);
 drop table abc;
create table abc(not  int);
 drop table abc;
create table abc(nowait  int);
 drop table abc;
create table abc(null  int);
 drop table abc;
create table abc(of  int);
 drop table abc;
create table abc(offline  int);
 drop table abc;
create table abc(on  int);
 drop table abc;
create table abc(online  int);
 drop table abc;
create table abc(or  int);
 drop table abc;
create table abc(order  int);
 drop table abc;
create table abc(rename  int);
 drop table abc;
create table abc(rows  int);
 drop table abc;
create table abc(select  int);
 drop table abc;
create table abc(session  int);
 drop table abc;
create table abc(set  int);
 drop table abc;
create table abc(start  int);
 drop table abc;
create table abc(table  int);
 drop table abc;
create table abc(then  int);
 drop table abc;
create table abc(to  int);
 drop table abc;
create table abc(trigger  int);
 drop table abc;
create table abc(union  int);
 drop table abc;
create table abc(update  int);
drop table if exists abc;
create table abc(f1 int);
alter table abc add user int;
 drop table abc;
create table abc(user  int);
 drop table abc;
create table abc(values  int);
 drop table abc;
create table abc(view  int);
 drop table abc;
create table abc(where  int);
 drop table abc;
create table abc(with  int);
 drop table abc;
create table abc(   char  int);
 drop table abc;
create table abc(   date  int);
 drop table abc;
create table abc(   decimal  int);
 drop table abc;
create table abc(   integer  int);
 drop table abc;
create table abc(   number  int);
 drop table abc;
create table abc(   raw  int);
 drop table abc;
create table abc(   varchar  int);
 drop table abc;
create table abc(   varchar2  int);
 drop table abc;
create table abc(   default  int);
 drop table abc;
create table abc(   null      int);
 drop table abc;
create table abc(   rowid  int);
 drop table abc;
create table abc(   rownum              int);
 drop table abc;
create table abc(   sysdate             int);
 drop table abc;
create table abc_(id int);
select * FROM abc_%;
drop table abc_;

--DTS2018101007001
drop table if exists test_keyword;
create table test_keyword (END int);
insert into test_keyword values (1);
commit;
select END from test_keyword order by END;

drop table if exists test_keyword;
create table test_keyword ( WHEN int);
insert into test_keyword values (1);
commit;
select  WHEN from test_keyword order by  WHEN;

drop table if exists test_keyword;
create table test_keyword (PRIOR int);
create table test_keyword ( THEN int);
create table test_keyword ( ELSE int);