CONN / AS SYSDBA
DROP USER IF EXISTS PL_DC2 CASCADE;
CREATE USER PL_DC2 IDENTIFIED BY Cantian_123456;
GRANT DBA TO PL_DC2;
GRANT EXECUTE ON DBE_DIAGNOSE TO PL_DC2;
conn PL_DC2/Cantian_123456@127.0.0.1:1611

--一、基本查找
--1.递归
CREATE OR REPLACE FUNCTION F1(C1 INT) RETURN INT IS
BEGIN
 IF C1 > 0 THEN
  RETURN PL_DC2.F1(C1 - 1) * C1;
 ELSE
  RETURN 1;
 END IF;
END;
/
SELECT F1(5);
SELECT F1(5,10);--找到但出错
CALL F1(5);--找到但出错

CREATE OR REPLACE FUNCTION PL_DC2.F1_2(C1 INT) RETURN INT IS
BEGIN
 IF C1 > 0 THEN
  RETURN PL_DC2.F1_2(C1 - 1) + C1;
 ELSE
  RETURN 0;
 END IF;
END;
/
SELECT F1_2(5);
SELECT F1_2(5,9);--找到但出错

CREATE TABLE T1(C1 INT);
CREATE OR REPLACE PROCEDURE P1(C1 INT) IS
BEGIN
 IF C1 > 0 THEN
  INSERT INTO T1 VALUES(C1);
  PL_DC2.P1(C1 - 1);
 ELSE
  INSERT INTO T1 VALUES(0);
 END IF;
 COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE PL_DC2.P1_2(C1 INT) IS
BEGIN
 IF C1 > 0 THEN
  INSERT INTO T1 VALUES(C1);
  PL_DC2.P1_2(C1 - 1);
 ELSE
  INSERT INTO T1 VALUES(0);
 END IF;
 COMMIT;
END;
/
CALL P1(1);
SELECT MAX(C1) FROM T1 ORDER BY C1;
CALL PL_DC2.P1_2(2);
CALL PL_DC2.P1_2('5th4');--找到但出错
SELECT MAX(C1) FROM T1 ORDER BY C1;

CREATE OR REPLACE SYNONYM L_SYN_F1 FOR PL_DC2.F1;
CREATE OR REPLACE SYNONYM L_SYN_F1_2 FOR PL_DC2.F1_2;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_F1 FOR PL_DC2.F1;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_F1_2 FOR PL_DC2.F1_2;
SELECT L_SYN_F1(3);
SELECT L_SYN_F1_2(3);
SELECT P_SYN_F1(3);
SELECT P_SYN_F1_2(3);

CREATE OR REPLACE SYNONYM L_SYN_P1 FOR PL_DC2.P1;
CREATE OR REPLACE SYNONYM L_SYN_P1_2 FOR PL_DC2.P1_2;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_P1 FOR PL_DC2.P1;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_P1_2 FOR PL_DC2.P1_2;
CALL L_SYN_P1(3);
SELECT MAX(C1) FROM T1 ORDER BY C1;
CALL L_SYN_P1_2(4);
SELECT MAX(C1) FROM T1 ORDER BY C1;
CALL P_SYN_P1(5);
SELECT MAX(C1) FROM T1 ORDER BY C1;
CALL P_SYN_P1_2(6);
SELECT MAX(C1) FROM T1 ORDER BY C1;


--2. 内置高级包或者用户自定义包
CREATE OR REPLACE PACKAGE PKG1 IS
 FUNCTION F1(C1 INT, C2 INT) RETURN INT;
 FUNCTION F2(C1 INT, C2 INT) RETURN INT;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG1 IS
 FUNCTION F1(C1 INT, C2 INT) RETURN INT IS
 BEGIN
  RETURN C1 + C2;
 END;
 FUNCTION F2(C1 INT, C2 INT) RETURN INT IS
 BEGIN
  RETURN C1 * C2;
 END;
END;
/

SELECT PKG1.F1(1,2);
SELECT PKG1.F3(1,2);--找到但出错
SELECT DBE_DIAGNOSE.DBA_USER_NAME(0);
SELECT DBE_DIAGNOSE.DBA_USER_NAME(0,'34534sddf');--找到但出错

CREATE OR REPLACE SYNONYM L_SYN_PKG1 FOR PKG1;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_PKG1 FOR PKG1;
CREATE OR REPLACE SYNONYM L_SYN_DIAGNOSE FOR SYS.DBE_DIAGNOSE;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_DIAGNOSE FOR SYS.DBE_DIAGNOSE;

SELECT L_SYN_PKG1.F1(1,2);
SELECT P_SYN_PKG1.F2(1,2);
SELECT L_SYN_DIAGNOSE.DBA_USER_NAME(0);
SELECT P_SYN_DIAGNOSE.DBA_USER_NAME(0);

--3.USER.NAME
CREATE OR REPLACE FUNCTION PL_DC2.F3(C1 INT) RETURN INT IS
BEGIN
 RETURN C1 * 10;
END;
/

SELECT PL_DC2.F3(1);
SELECT PL_DC2.F3('43r43rrr');--找到但出错

CREATE OR REPLACE SYNONYM L_SYN_F3 FOR PL_DC2.F3;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_F3 FOR PL_DC2.F3;
CREATE OR REPLACE SYNONYM L_SYN_F4 FOR PL_DC1.F1;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_F4 FOR PL_DC1.F1;
SELECT L_SYN_F3(10);
SELECT P_SYN_F3(11);
SELECT L_SYN_F4(10);
SELECT P_SYN_F4(11);

--4.AS PUBLIC OBJECT
CREATE OR REPLACE PACKAGE "PUBLIC".PKG4 IS
 FUNCTION F1(C1 INT, C2 INT) RETURN INT;
END;
/
CREATE OR REPLACE PACKAGE BODY "PUBLIC".PKG4 IS
 FUNCTION F1(C1 INT, C2 INT) RETURN INT IS
 BEGIN
  RETURN C1 * C2;
 END;
END;
/
SELECT PKG4.F1(11,23);
SELECT PKG4.F2(11,23);--找到但出错

CREATE OR REPLACE SYNONYM L_SYN_PKG4 FOR "PUBLIC".PKG4;
CREATE OR REPLACE PUBLIC SYNONYM P_SYN_PKG4 FOR "PUBLIC".PKG4;
SELECT L_SYN_PKG4.F1(11,23);
SELECT P_SYN_PKG4.F1(11,23);

--6.RETURN ERROR package user.name1 not exist
SELECT PL_DC4.F1(1);
CALL PL_DC4.P1(1);

--二、优先级测试
--递归
--用户自定义包
--系统包
--user.name
--public的包

--递归>自定义包
CREATE OR REPLACE PACKAGE PKG1 IS
 FUNCTION F1(C1 INT) RETURN INT;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG1 IS
 FUNCTION F1(C1 INT) RETURN INT IS
 BEGIN
  RETURN C1 * 100 + 11;
 END;
END;
/
SELECT PKG1.F1(1);

DROP USER IF EXISTS PKG1;
CREATE USER PKG1 IDENTIFIED BY Cantian_123456;
GRANT DBA TO PKG1;
CREATE OR REPLACE FUNCTION PKG1.F1(C1 INT) RETURN INT IS
BEGIN
 IF C1 > 0 THEN
  RETURN PKG1.F1(C1 - 1) + C1;
 ELSE
  RETURN 0;
 END IF;
END;
/

CONN PKG1/Cantian_123456@127.0.0.1:1611
SELECT PKG1.F1(10);

CONN PL_DC2/Cantian_123456@127.0.0.1:1611
--用户自定义包>系统包
CREATE OR REPLACE PACKAGE DBE_DIAGNOSE IS
 FUNCTION DBA_USER_NAME(C1 INT) RETURN INT;
END;
/

CREATE OR REPLACE PACKAGE BODY DBE_DIAGNOSE IS
 FUNCTION DBA_USER_NAME(C1 INT) RETURN INT IS
 BEGIN
  RETURN C1 * 10 + 1;
 END;
END;
/
SELECT DBE_DIAGNOSE.DBA_USER_NAME(1);

DROP PACKAGE DBE_DIAGNOSE;
SELECT DBE_DIAGNOSE.DBA_USER_NAME(1);

--系统包>USER.NAME
DROP USER IF EXISTS DBE_DIAGNOSE CASCADE;
CREATE USER DBE_DIAGNOSE IDENTIFIED BY Cantian_123456;
CREATE OR REPLACE FUNCTION DBE_DIAGNOSE.DBA_USER_NAME(C1 INT) RETURN INT IS
BEGIN
 RETURN C1 * 10 + 2;
END;
/
SELECT DBE_DIAGNOSE.DBA_USER_NAME(1);
DROP USER IF EXISTS DBE_DIAGNOSE CASCADE;

--USER.NAME>PUBLIC OBJECT
DROP USER IF EXISTS PKG8 CASCADE;
CREATE USER PKG8 IDENTIFIED BY Cantian_123456;
CREATE OR REPLACE FUNCTION PKG8.F1(C1 INT) RETURN INT IS
BEGIN
 RETURN C1 * 10 + 8;
END;
/

CREATE OR REPLACE PACKAGE "PUBLIC".PKG8 IS
 FUNCTION F1(C1 INT) RETURN INT;
END;
/

CREATE OR REPLACE PACKAGE BODY "PUBLIC".PKG8 IS
 FUNCTION F1(C1 INT) RETURN INT IS
 BEGIN
  RETURN C1 + 9;
 END;
END;
/

SELECT PKG8.F1(1);
DROP FUNCTION PKG8.F1;
SELECT PKG8.F1(1);

--报错 package current.name1 does not exist
SELECT PKG9.F1(1);

CONN / AS SYSDBA
DROP USER IF EXISTS PL_DC2 CASCADE;
DROP USER IF EXISTS PKG1 CASCADE;