---
--- SHRINK SPACE TEST
---
CREATE TABLESPACE SHK_TBLSPC DATAFILE 'SHK001' SIZE 32M AUTOEXTEND ON NEXT 32M;

--SHRINK SYNTAX TEST
DROP TABLE IF EXISTS SHK_SYNTAX_001;
CREATE TABLE SHK_SYNTAX_001 (ID INT) TABLESPACE SHK_TBLSPC;
ALTER TABLE SHK_SYNTAX_001 SHRINK SPACE;
ALTER TABLE SHK_SYNTAX_001 SHRINK SPACE COMPACT;
ALTER TABLE SHK_SYNTAX_001 SHRINK SPACE COMPACT CASCADE;
ALTER TABLE SHK_SYNTAX_001 SHRINK SPACE CASCADE;
DROP TABLE SHK_SYNTAX_001 PURGE;

--[SHRINK SPACE COMPACT] NORMAL TABLE WITH NO DATA
DROP TABLE IF EXISTS SHK_SPC_CMP_001 PURGE;
CREATE TABLE SHK_SPC_CMP_001 (ID INT, NAME CHAR(200) DEFAULT 'SHRINK TEST', TT CLOB DEFAULT 'SHRINK CLOB') TABLESPACE SHK_TBLSPC;
ALTER TABLE SHK_SPC_CMP_001 SHRINK SPACE COMPACT;

--[SHRINK SPACE COMPACT] NORMAL TABLE WITH DATA, NO PAGE HOLE
INSERT INTO SHK_SPC_CMP_001 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 
ALTER TABLE SHK_SPC_CMP_001 SHRINK SPACE COMPACT;

--[SHRINK SPACE COMPACT] NORMAL TABLE WITH DATA, HAS HOLE PAGE
DELETE FROM SHK_SPC_CMP_001 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_CMP_001 SHRINK SPACE COMPACT;

DELETE FROM SHK_SPC_CMP_001;
ALTER TABLE SHK_SPC_CMP_001 SHRINK SPACE COMPACT;

--[SHRINK SPACE COMPACT] NORMAL TABLE WITH UNIQUE INDEX
CREATE UNIQUE INDEX SHK_SPC_CMP_IDX_001 ON SHK_SPC_CMP_001 (ID) TABLESPACE SHK_TBLSPC;;
INSERT INTO SHK_SPC_CMP_001 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 

DELETE FROM SHK_SPC_CMP_001 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_CMP_001 SHRINK SPACE COMPACT;

DELETE FROM SHK_SPC_CMP_001;
ALTER TABLE SHK_SPC_CMP_001 SHRINK SPACE COMPACT;

DROP TABLE SHK_SPC_CMP_001 PURGE;

--[SHRINK SPACE COMPACT] PARTITION TABLE WITH NO DATA
DROP TABLE IF EXISTS SHK_SPC_CMP_002 PURGE;
CREATE TABLE SHK_SPC_CMP_002 (ID INT, NAME CHAR(200) DEFAULT 'SHRINK TEST', TT CLOB DEFAULT 'SHRINK CLOB')
PARTITION BY RANGE (ID)
(
PARTITION P1 VALUES LESS THAN (15),
PARTITION P2 VALUES LESS THAN (25),
PARTITION P3 VALUES LESS THAN (MAXVALUE)
)
TABLESPACE SHK_TBLSPC;
ALTER TABLE SHK_SPC_CMP_002 SHRINK SPACE COMPACT;

--[SHRINK SPACE COMPACT] PARTITION TABLE WITH DATA, NO PAGE HOLE
INSERT INTO SHK_SPC_CMP_002 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 
ALTER TABLE SHK_SPC_CMP_002 SHRINK SPACE COMPACT;

--[SHRINK SPACE COMPACT] PARTITION TABLE WITH DATA, HAS HOLE PAGE
DELETE FROM SHK_SPC_CMP_002 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_CMP_002 SHRINK SPACE COMPACT;

DELETE FROM SHK_SPC_CMP_002;
ALTER TABLE SHK_SPC_CMP_002 SHRINK SPACE COMPACT;

--[SHRINK SPACE COMPACT] PARTITION TABLE WITH UNIQUE INDEX
CREATE UNIQUE INDEX SHK_SPC_CMP_IDX_002 ON SHK_SPC_CMP_002 (ID) LOCAL TABLESPACE SHK_TBLSPC;;
INSERT INTO SHK_SPC_CMP_002 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 

DELETE FROM SHK_SPC_CMP_002 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_CMP_002 SHRINK SPACE COMPACT;

DELETE FROM SHK_SPC_CMP_002;
ALTER TABLE SHK_SPC_CMP_002 SHRINK SPACE COMPACT;

DROP TABLE SHK_SPC_CMP_002 PURGE;

--[SHRINK SPACE] NORMAL TABLE WITH NO DATA
DROP TABLE IF EXISTS SHK_SPC_001 PURGE;
CREATE TABLE SHK_SPC_001 (ID INT, NAME CHAR(200) DEFAULT 'SHRINK TEST', TT CLOB DEFAULT 'SHRINK CLOB') TABLESPACE SHK_TBLSPC;
ALTER TABLE SHK_SPC_001 SHRINK SPACE;

--[SHRINK SPACE] NORMAL TABLE WITH DATA, NO PAGE HOLE
INSERT INTO SHK_SPC_001 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 
ALTER TABLE SHK_SPC_001 SHRINK SPACE;

--[SHRINK SPACE] NORMAL TABLE WITH DATA, HAS HOLE PAGE
DELETE FROM SHK_SPC_001 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_001 SHRINK SPACE;

DELETE FROM SHK_SPC_001;
ALTER TABLE SHK_SPC_001 SHRINK SPACE;

--[SHRINK SPACE] NORMAL TABLE WITH UNIQUE INDEX
CREATE UNIQUE INDEX SHK_SPC_IDX_001 ON SHK_SPC_001 (ID) TABLESPACE SHK_TBLSPC;;
INSERT INTO SHK_SPC_001 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 

DELETE FROM SHK_SPC_001 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_001 SHRINK SPACE;

DELETE FROM SHK_SPC_001;
ALTER TABLE SHK_SPC_001 SHRINK SPACE;

DROP TABLE SHK_SPC_001 PURGE;

--[SHRINK SPACE] PARTITION TABLE WITH NO DATA
DROP TABLE IF EXISTS SHK_SPC_002 PURGE;
CREATE TABLE SHK_SPC_002 (ID INT, NAME CHAR(200) DEFAULT 'SHRINK TEST', TT CLOB DEFAULT 'SHRINK CLOB')
PARTITION BY RANGE (ID)
(
PARTITION P1 VALUES LESS THAN (15),
PARTITION P2 VALUES LESS THAN (25),
PARTITION P3 VALUES LESS THAN (MAXVALUE)
)
TABLESPACE SHK_TBLSPC;
ALTER TABLE SHK_SPC_002 SHRINK SPACE;

--[SHRINK SPACE] PARTITION TABLE WITH DATA, NO PAGE HOLE
INSERT INTO SHK_SPC_002 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 
ALTER TABLE SHK_SPC_002 SHRINK SPACE;

--[SHRINK SPACE] PARTITION TABLE WITH DATA, HAS HOLE PAGE
DELETE FROM SHK_SPC_002 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_002 SHRINK SPACE;

DELETE FROM SHK_SPC_002;
ALTER TABLE SHK_SPC_002 SHRINK SPACE;

--[SHRINK SPACE] PARTITION TABLE WITH UNIQUE INDEX
CREATE UNIQUE INDEX SHK_SPC_IDX_002 ON SHK_SPC_002 (ID) LOCAL TABLESPACE SHK_TBLSPC;;
INSERT INTO SHK_SPC_002 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40; 

DELETE FROM SHK_SPC_002 WHERE ID <= 20 OR ID >= 30;
ALTER TABLE SHK_SPC_002 SHRINK SPACE;

DELETE FROM SHK_SPC_002;
ALTER TABLE SHK_SPC_002 SHRINK SPACE;

DROP TABLE SHK_SPC_002 PURGE;

--[SHRINK SPACE AFTER COMPACT] NORMAL TABLE
DROP TABLE IF EXISTS SHK_SPC_AFT_CMP_001 PURGE;
CREATE TABLE SHK_SPC_AFT_CMP_001 (ID INT, NAME CHAR(200) DEFAULT 'SHRINK TEST', TT CLOB DEFAULT 'SHRINK CLOB') TABLESPACE SHK_TBLSPC;
CREATE UNIQUE INDEX SHK_SPC_AFT_CMP_IDX_001 ON SHK_SPC_AFT_CMP_001 (ID) TABLESPACE SHK_TBLSPC;;

INSERT INTO SHK_SPC_AFT_CMP_001 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40;
DELETE FROM SHK_SPC_AFT_CMP_001 WHERE ID <= 20 OR ID >= 30;

ALTER TABLE SHK_SPC_AFT_CMP_001 SHRINK SPACE COMPACT;
ALTER TABLE SHK_SPC_AFT_CMP_001 SHRINK SPACE COMPACT;
ALTER TABLE SHK_SPC_AFT_CMP_001 SHRINK SPACE;
ALTER TABLE SHK_SPC_AFT_CMP_001 SHRINK SPACE;

DROP TABLE SHK_SPC_AFT_CMP_001 PURGE;

--[SHRINK SPACE AFTER COMPACT] PARTITION TABLE
DROP TABLE IF EXISTS SHK_SPC_AFT_CMP_002 PURGE;
CREATE TABLE SHK_SPC_AFT_CMP_002 (ID INT, NAME CHAR(200) DEFAULT 'SHRINK TEST', TT CLOB DEFAULT 'SHRINK CLOB')
PARTITION BY RANGE (ID)
(
PARTITION P1 VALUES LESS THAN (15),
PARTITION P2 VALUES LESS THAN (25),
PARTITION P3 VALUES LESS THAN (MAXVALUE)
)
TABLESPACE SHK_TBLSPC;
CREATE UNIQUE INDEX SHK_SPC_AFT_CMP_IDX_002 ON SHK_SPC_AFT_CMP_002 (ID) TABLESPACE SHK_TBLSPC;

INSERT INTO SHK_SPC_AFT_CMP_002 (ID) SELECT ID FROM SYS.SYS_TABLES WHERE USER# = 0 AND ID < 40;
DELETE FROM SHK_SPC_AFT_CMP_002 WHERE ID <= 20 OR ID >= 30;

ALTER TABLE SHK_SPC_AFT_CMP_002 SHRINK SPACE COMPACT;
ALTER TABLE SHK_SPC_AFT_CMP_002 SHRINK SPACE COMPACT;
ALTER TABLE SHK_SPC_AFT_CMP_002 SHRINK SPACE;
ALTER TABLE SHK_SPC_AFT_CMP_002 SHRINK SPACE;

DROP TABLE SHK_SPC_AFT_CMP_002 PURGE;

--[SHRINK CHAIN TABLE] SHRINK CHAIN ROW
DROP TABLE IF EXISTS SHK_CHAIN_TABLE_1;
CREATE TABLE SHK_CHAIN_TABLE_1(ID INT, A VARCHAR(4000), B VARCHAR(4000), C VARCHAR(4000), D VARCHAR(4000)) TABLESPACE SHK_TBLSPC;

INSERT INTO SHK_CHAIN_TABLE_1 VALUES(1, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_1 VALUES(2, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_1 VALUES(3, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_1 VALUES(4, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_1 VALUES(5, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_1 SELECT * FROM SHK_CHAIN_TABLE_1;
INSERT INTO SHK_CHAIN_TABLE_1 SELECT * FROM SHK_CHAIN_TABLE_1;
INSERT INTO SHK_CHAIN_TABLE_1 SELECT * FROM SHK_CHAIN_TABLE_1;

DELETE FROM SHK_CHAIN_TABLE_1 WHERE ID != 4;
ALTER TABLE SHK_CHAIN_TABLE_1 SHRINK SPACE COMPACT;
ALTER TABLE SHK_CHAIN_TABLE_1 SHRINK SPACE;

DROP TABLE SHK_CHAIN_TABLE_1 PURGE;

--[SHRINK CHAIN TABLE] SHRINK CHAIN ROW
DROP TABLE IF EXISTS SHK_CHAIN_TABLE_2;
CREATE TABLE SHK_CHAIN_TABLE_2(ID INT, A VARCHAR(4000), B VARCHAR(4000), C VARCHAR(4000), D VARCHAR(4000)) TABLESPACE SHK_TBLSPC;

INSERT INTO SHK_CHAIN_TABLE_2 VALUES(1, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_2 VALUES(2, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_2 VALUES(3, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_2 VALUES(4, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_2 VALUES(5, LPAD('A',4000,'A'), LPAD('B',4000,'B'), LPAD('C',4000,'C'),'D');
INSERT INTO SHK_CHAIN_TABLE_2 SELECT * FROM SHK_CHAIN_TABLE_2;
INSERT INTO SHK_CHAIN_TABLE_2 SELECT * FROM SHK_CHAIN_TABLE_2;
INSERT INTO SHK_CHAIN_TABLE_2 SELECT * FROM SHK_CHAIN_TABLE_2;

DELETE FROM SHK_CHAIN_TABLE_2 WHERE ID != 5;
ALTER TABLE SHK_CHAIN_TABLE_2 SHRINK SPACE COMPACT;
ALTER TABLE SHK_CHAIN_TABLE_2 SHRINK SPACE;

DROP TABLE SHK_CHAIN_TABLE_2 PURGE;

--[SHRINK WITH FLASHBACK]
DROP TABLE IF EXISTS SHK_SPC_FB_1;
CREATE TABLE SHK_SPC_FB_1 (ID INT PRIMARY KEY) TABLESPACE SHK_TBLSPC;
INSERT INTO SHK_SPC_FB_1 VALUES (10);
INSERT INTO SHK_SPC_FB_1 VALUES (20);
INSERT INTO SHK_SPC_FB_1 VALUES (30);

TRUNCATE TABLE SHK_SPC_FB_1;

INSERT INTO SHK_SPC_FB_1 VALUES (10);
ALTER TABLE SHK_SPC_FB_1 SHRINK SPACE COMPACT;
FLASHBACK TABLE SHK_SPC_FB_1 TO BEFORE TRUNCATE FORCE;

TRUNCATE TABLE SHK_SPC_FB_1;

INSERT INTO SHK_SPC_FB_1 VALUES (10);
ALTER TABLE SHK_SPC_FB_1 SHRINK SPACE;
FLASHBACK TABLE SHK_SPC_FB_1 TO BEFORE TRUNCATE FORCE;

DROP TABLE SHK_SPC_FB_1;

DROP TABLE IF EXISTS SHK_SPC_FB_2;
CREATE TABLE SHK_SPC_FB_2 (ID INT, FF INT)
PARTITION BY RANGE (ID)
(
PARTITION P1 VALUES LESS THAN (20),
PARTITION P2 VALUES LESS THAN (MAXVALUE)
) TABLESPACE SHK_TBLSPC;
CREATE UNIQUE INDEX IDX_SHK_SPC_FB_2_1 ON SHK_SPC_FB_2(ID) LOCAL TABLESPACE SHK_TBLSPC;
CREATE UNIQUE INDEX IDX_SHK_SPC_FB_2_2 ON SHK_SPC_FB_2(FF) TABLESPACE SHK_TBLSPC;

INSERT INTO SHK_SPC_FB_2 VALUES (10, 10);
INSERT INTO SHK_SPC_FB_2 VALUES (20, 20);
INSERT INTO SHK_SPC_FB_2 VALUES (30, 30);

ALTER TABLE SHK_SPC_FB_2 TRUNCATE PARTITION P1;

INSERT INTO SHK_SPC_FB_2 VALUES (10, 10);

ALTER INDEX IDX_SHK_SPC_FB_2_2 ON SHK_SPC_FB_2 REBUILD;

INSERT INTO SHK_SPC_FB_2 VALUES (10, 10);
ALTER TABLE SHK_SPC_FB_2 SHRINK SPACE COMPACT;
FLASHBACK TABLE SHK_SPC_FB_2 PARTITION P1 TO BEFORE TRUNCATE FORCE;

ALTER TABLE SHK_SPC_FB_2 TRUNCATE PARTITION P1;

INSERT INTO SHK_SPC_FB_2 VALUES (10, 10);

ALTER INDEX IDX_SHK_SPC_FB_2_2 ON SHK_SPC_FB_2 REBUILD;

INSERT INTO SHK_SPC_FB_2 VALUES (10, 10);
ALTER TABLE SHK_SPC_FB_2 SHRINK SPACE;
FLASHBACK TABLE SHK_SPC_FB_2 PARTITION P1 TO BEFORE TRUNCATE FORCE;

DROP TABLE SHK_SPC_FB_2;

--CLEANUP
PURGE TABLESPACE SHK_TBLSPC;
ALTER SYSTEM CHECKPOINT;

--dts DTS2018091410246
drop table if exists hzy_shrink0; 
CREATE TABLE hzy_shrink0(C_ID INT,
C_D_ID bigint NOT NULL,
C_W_ID tinyint unsigned NOT NULL,
C_FIRST VARCHAR(64) NOT NULL,
C_MIDDLE CHAR(2),
C_LAST VARCHAR(64) NOT NULL,
C_STREET_1 VARCHAR(20) NOT NULL,
C_STREET_2 VARCHAR(8000),
C_CITY VARCHAR(20) NOT NULL,
C_STATE CHAR(2) NOT NULL,
C_ZIP CHAR(9) NOT NULL,
C_PHONE CHAR(16) NOT NULL,
C_SINCE TIMESTAMP,
C_CREDIT CHAR(2) NOT NULL,
C_CREDIT_LIM NUMERIC(12,2),
C_DISCOUNT NUMERIC(4,4),
C_BALANCE NUMERIC(12,2),
C_YTD_PAYMENT REAL NOT NULL,
C_PAYMENT_CNT NUMBER NOT NULL,
C_DELIVERY_CNT BOOL NOT NULL,
C_END DATE NOT NULL,
C_VCHAR VARCHAR(1000),
C_DATA LONG,
C_TEXT BLOB,
C_CLOB CLOB,
primary key (c_id,c_d_id,c_w_id));
insert into  hzy_shrink0 select 0,0,0,'AA'||'is0cmvls','OE','AA'||'BAR0BARBAR','bkili'||'0'||'fcxcle'||'0','QNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSS','dyf'||'0'||'rya'||'0','uq',4800||'0',940||'0'||205||'0','2017-12-31 10:51:47','GC',50000.0,0.4361328,-10.0,10.0,1,true,'2017-12-31 10:51:47','QVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECC348493214893542NPFZCSYKXXYSCDSF'||'0','QVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSF1','1234354587643123455213445656723123424554566776763221132454566768767433242323445453565654542323','QVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSFQVLDETANRBRBURBMZQUJSHOQNGGSMNTECCIPRIIRDHIRWIYNPFZCSYKXXYSCDSF1CLOB';
commit;
CREATE or replace procedure nebula_dml_interval_proc_001(startall int,endall int) as
i INT;
BEGIN
 if startall <= endall then
  FOR i IN startall..endall LOOP
        insert into hzy_shrink0 select c_id+i,c_d_id+i,c_w_id+i,'AA'||'iscmvls',c_middle,'AA'||'BAR'||i||'ddBARBAR',c_street_1,c_street_2,c_city,c_state,c_zip,c_phone,c_since+i,c_credit,c_credit_lim,c_discount,c_balance,c_ytd_payment,c_payment_cnt,c_delivery_cnt,c_end+i,c_vchar,c_data,c_text,c_clob from hzy_shrink0 where c_id=0;commit;
  END LOOP;
 end if;
END;
/
call nebula_dml_interval_proc_001(1,100);
delete from hzy_shrink0 where c_id=0;
commit;
select count(*) from hzy_shrink0;

drop table if exists hzy_shrink1;
CREATE TABLE hzy_shrink1(C_ID INT,C_D_ID bigint NOT NULL,C_W_ID tinyint unsigned NOT NULL,C_FIRST VARCHAR(64) NOT NULL,C_MIDDLE CHAR(2),C_LAST VARCHAR(64) NOT NULL,C_STREET_1 VARCHAR(20) NOT NULL,C_STREET_2 VARCHAR(8000),C_CITY VARCHAR(20) NOT NULL,C_STATE CHAR(2) NOT NULL,C_ZIP CHAR(9) NOT NULL,C_PHONE CHAR(16) NOT NULL,C_SINCE TIMESTAMP,C_CREDIT CHAR(2) NOT NULL,C_CREDIT_LIM NUMERIC(12,2),C_DISCOUNT NUMERIC(4,4),C_BALANCE NUMERIC(12,2),C_YTD_PAYMENT REAL NOT NULL,C_PAYMENT_CNT NUMBER NOT NULL,C_DELIVERY_CNT BOOL NOT NULL,C_END DATE NOT NULL,C_VCHAR VARCHAR(1000) NOT NULL,C_DATA LONG,C_TEXT BLOB,C_CLOB CLOB)PARTITION BY RANGE(C_ID)INTERVAL(100)(PARTITION PART_1 VALUES LESS THAN (201),PARTITION PART_2 VALUES LESS THAN (401),PARTITION PART_3 VALUES LESS THAN (601),PARTITION PART_4 VALUES LESS THAN (801),PARTITION PART_5 VALUES LESS THAN (1001),PARTITION PART_6 VALUES LESS THAN (1201),PARTITION PART_7 VALUES LESS THAN (1401),PARTITION PART_8 VALUES LESS THAN (1601),PARTITION PART_9 VALUES LESS THAN (1801));
insert into hzy_shrink1(c_id,c_d_id,c_w_id,c_first,c_middle,c_last,c_street_1,c_street_2,c_city,c_state,c_zip,c_phone,c_since,c_credit,c_credit_lim,c_discount,c_balance,c_ytd_payment,c_payment_cnt,c_delivery_cnt,c_end,c_vchar,c_data,c_text,c_clob) select c_id,c_d_id,c_w_id,c_first,c_middle,c_last,c_street_1,c_street_2,c_city,c_state,c_zip,c_phone,c_since,c_credit,c_credit_lim,c_discount,c_balance,c_ytd_payment,c_payment_cnt,c_delivery_cnt,c_end,c_vchar,c_data,c_text,c_clob from hzy_shrink0;
alter table hzy_shrink1  add column  v_long long default lpad('sbfacwjdafgjyjhfpyxcpmnutcjxrbfgxxbm',500,'yxcfgdsgtcsdsjxrbxxbm');
update hzy_shrink1 set v_long=null;
alter table hzy_shrink1 shrink space;

--DTS2018120404387
CREATE TABLESPACE SHK_SPC_MAP DATAFILE 'SHKMAP' SIZE 32M AUTOEXTEND ON NEXT 32M;
CREATE TABLE SHK_MAP(order_index int, xx varchar(8000)) TABLESPACE SHK_SPC_MAP;
declare 
i integer;
begin
for i in 1 .. 1019 loop
insert into SHK_MAP values(1, lpad(' ', 8000, 'ab'));
end loop;
commit;
end;
/
insert into SHK_MAP values(2, lpad(' ', 6028, 'b'));
insert into SHK_MAP values(3, lpad(' ', 500, 'c'));
insert into SHK_MAP values(3, lpad(' ', 500, 'c'));
insert into SHK_MAP values(4, lpad(' ', 300, 'd'));
commit;
delete from SHK_MAP where order_index = 3;
commit;
ALTER TABLE SHK_MAP SHRINK SPACE;
commit;
insert into SHK_MAP values(5, lpad(' ', 7000, 'b'));

--ST1224-883
CREATE TABLE mini_table(c_id int, xx varchar(8000)) TABLESPACE SHK_SPC_MAP;
insert into mini_table values(1, lpad(' ', 8000, 'a'));
insert into mini_table values(2, lpad(' ', 8000, 'a'));
insert into mini_table values(3, lpad(' ', 8000, 'a'));
commit;
ALTER TABLE mini_table SHRINK SPACE;
insert into mini_table values(4, lpad(' ', 8000, 'a'));
insert into mini_table values(5, lpad(' ', 8000, 'a'));
insert into mini_table values(6, lpad(' ', 8000, 'a'));
insert into mini_table values(7, lpad(' ', 8000, 'a'));
select c_id from mini_table;

DROP TABLESPACE SHK_SPC_MAP INCLUDING CONTENTS AND DATAFILES;

--shrink ratio
drop table if exists shrink_ratio;
create table shrink_ratio(i int,name varchar(8000));
create unique index shrink_ratio_idx on shrink_ratio(i);
declare 
i integer;
begin
for i in 1 .. 10000 loop
insert into shrink_ratio values(i, lpad(' ', 8000, 'ab'));
end loop;
commit;
end;
/
delete from shrink_ratio where mod(i,3)=0;
alter table shrink_ratio shrink space percent -1;
alter table shrink_ratio shrink space percent 0;
alter table shrink_ratio shrink space percent 101;
alter table shrink_ratio shrink space percent 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111;
alter table shrink_ratio shrink space percent 50.5;
alter table shrink_ratio shrink space compact percent 0;
alter table shrink_ratio shrink space compact percent 101;
alter table shrink_ratio shrink space compact percent 50.5;
alter table shrink_ratio shrink space percent 50;
alter table shrink_ratio shrink space percent;
alter table shrink_ratio shrink space percent 100 100;
drop table shrink_ratio;

create tablespace test_space datafile 'test_datafile_1' size 8M, 'test_datafile_2' size 1G extent autoallocate encryption;
create table test_space(c_id int,c_d_id  bigint NOT NULL,c_w_id tinyint unsigned NOT NULL,c_first varchar(40) NOT NULL,c_long long,c_last varchar(50) NOT NULL,c_street_1 varchar(20) NOT NULL,c_street_2 varchar(20),c_city varchar(20) NOT NULL,c_state char(2) NOT NULL,c_zip char(9) NOT NULL,c_phone char(40) NOT NULL,c_since timestamp,c_credit char(2) NOT NULL,c_credit_lim numeric(12,2),c_discount numeric(4,4),c_balance numeric(12,2),c_ytd_payment real NOT NULL,c_payment_cnt number NOT NULL,c_delivery_cnt bool NOT NULL,c_end date NOT NULL,c_binary binary(1500),c_varbinary varbinary(7000),c_vchar varchar2(7000),c_raw raw(7000),c_blob blob,c_clob clob,c_image image,primary key(c_id,c_d_id,c_w_id))tablespace test_space;
insert into test_space select 0,0,0,'AA'||'is0cmvls',lpad('lonADFGgabcd1234VS',500,'abceEFG234styop'),'AA'||'BAR0BARBAR','bkilifcxcle'||'0','pmbwaj','dyfa','uq',4800||'0',940||'0'||205||'0','2017-12-30 10:51:47','GC',50000.0,0.4361328,-10.0,10.0,1,true,'2017-12-30 10:51:47',lpad('abcdefGHopqrs1234',500,'1234EDAVDSergad'),lpad('varbinary1234RAFTDS',500,'VARBIN6789ARYabceef'),lpad('1234ABCDRFGHopqrstuvwxyz8',500,'ABfgCDefgh'),lpad('abcdef1234456789',500,'123456789abcdef'),lpad('124324543256546324554354325',8000,'7687389015'),lpad('sbfacwjpbvpgthpyxcpmnutcjdfaxrbxxbm',8000,'yxcpmnutcjxrbxxbm'),lpad('image1234RASRabdeff',8000,'yxcfgdsgtcjxrbxxbm');
commit;
CREATE or replace procedure proc_test_space(startall int,endall int) as
i INT;
BEGIN
  FOR i IN startall..endall LOOP
        insert into test_space select c_id+i,c_d_id+i,c_w_id+100000*i,'AA'||'is'||i||'cmvls',c_long,'AA'||'BAR'||i||'ddBARBAR',c_street_1,c_street_2,c_city,c_state,c_zip,'940'||i||'205'||i,c_since+i,c_credit,c_credit_lim,c_discount,c_balance,c_ytd_payment,c_payment_cnt,c_delivery_cnt,c_end+i,c_binary,c_varbinary,c_vchar,c_raw,c_blob,c_clob,c_image from test_space where c_id=0;commit;
  END LOOP;
END;
/
call proc_test_space(1,1000);
create index index_test_space on test_space(c_id);

--delete+shrink
delete from test_space;
alter tablespace test_space shrink space keep 2M;

--drop index+shrink
drop index index_test_space on test_space;
alter tablespace test_space shrink space keep 2M;

--drop table+shrink
drop table test_space;
alter tablespace test_space shrink space keep 2M;

--truncate table+shrink
drop tablespace test_space including contents and datafiles;
create tablespace test_space datafile 'test_datafile_1' size 8M, 'test_datafile_2' size 1G extent autoallocate encryption;
create table test_space(c_id int,c_d_id  bigint NOT NULL,c_w_id tinyint unsigned NOT NULL,c_first varchar(40) NOT NULL,c_long long,c_last varchar(50) NOT NULL,c_street_1 varchar(20) NOT NULL,c_street_2 varchar(20),c_city varchar(20) NOT NULL,c_state char(2) NOT NULL,c_zip char(9) NOT NULL,c_phone char(40) NOT NULL,c_since timestamp,c_credit char(2) NOT NULL,c_credit_lim numeric(12,2),c_discount numeric(4,4),c_balance numeric(12,2),c_ytd_payment real NOT NULL,c_payment_cnt number NOT NULL,c_delivery_cnt bool NOT NULL,c_end date NOT NULL,c_binary binary(1500),c_varbinary varbinary(7000),c_vchar varchar2(7000),c_raw raw(7000),c_blob blob,c_clob clob,c_image image,primary key(c_id,c_d_id,c_w_id)) partition by range(c_id) (partition p1 values less than(MAXVALUE))tablespace test_space;
insert into test_space select 0,0,0,'AA'||'is0cmvls',lpad('lonADFGgabcd1234VS',500,'abceEFG234styop'),'AA'||'BAR0BARBAR','bkilifcxcle'||'0','pmbwaj','dyfa','uq',4800||'0',940||'0'||205||'0','2017-12-30 10:51:47','GC',50000.0,0.4361328,-10.0,10.0,1,true,'2017-12-30 10:51:47',lpad('abcdefGHopqrs1234',500,'1234EDAVDSergad'),lpad('varbinary1234RAFTDS',500,'VARBIN6789ARYabceef'),lpad('1234ABCDRFGHopqrstuvwxyz8',500,'ABfgCDefgh'),lpad('abcdef1234456789',500,'123456789abcdef'),lpad('124324543256546324554354325',8000,'7687389015'),lpad('sbfacwjpbvpgthpyxcpmnutcjdfaxrbxxbm',8000,'yxcpmnutcjxrbxxbm'),lpad('image1234RASRabdeff',8000,'yxcfgdsgtcjxrbxxbm');
commit;
call proc_test_space(1,1000);
truncate table test_space;
alter tablespace test_space shrink space keep 2M;

--truncate partition + shrink
drop tablespace test_space including contents and datafiles;
create tablespace test_space datafile 'test_datafile_1' size 8M, 'test_datafile_2' size 1G extent autoallocate encryption;
create table test_space(c_id int,c_d_id  bigint NOT NULL,c_w_id tinyint unsigned NOT NULL,c_first varchar(40) NOT NULL,c_long long,c_last varchar(50) NOT NULL,c_street_1 varchar(20) NOT NULL,c_street_2 varchar(20),c_city varchar(20) NOT NULL,c_state char(2) NOT NULL,c_zip char(9) NOT NULL,c_phone char(40) NOT NULL,c_since timestamp,c_credit char(2) NOT NULL,c_credit_lim numeric(12,2),c_discount numeric(4,4),c_balance numeric(12,2),c_ytd_payment real NOT NULL,c_payment_cnt number NOT NULL,c_delivery_cnt bool NOT NULL,c_end date NOT NULL,c_binary binary(1500),c_varbinary varbinary(7000),c_vchar varchar2(7000),c_raw raw(7000),c_blob blob,c_clob clob,c_image image,primary key(c_id,c_d_id,c_w_id)) partition by range(c_id) (partition p1 values less than(MAXVALUE))tablespace test_space;
insert into test_space select 0,0,0,'AA'||'is0cmvls',lpad('lonADFGgabcd1234VS',500,'abceEFG234styop'),'AA'||'BAR0BARBAR','bkilifcxcle'||'0','pmbwaj','dyfa','uq',4800||'0',940||'0'||205||'0','2017-12-30 10:51:47','GC',50000.0,0.4361328,-10.0,10.0,1,true,'2017-12-30 10:51:47',lpad('abcdefGHopqrs1234',500,'1234EDAVDSergad'),lpad('varbinary1234RAFTDS',500,'VARBIN6789ARYabceef'),lpad('1234ABCDRFGHopqrstuvwxyz8',500,'ABfgCDefgh'),lpad('abcdef1234456789',500,'123456789abcdef'),lpad('124324543256546324554354325',8000,'7687389015'),lpad('sbfacwjpbvpgthpyxcpmnutcjdfaxrbxxbm',8000,'yxcpmnutcjxrbxxbm'),lpad('image1234RASRabdeff',8000,'yxcfgdsgtcjxrbxxbm');
commit;
call proc_test_space(1,1000);
alter table test_space truncate partition p1;
alter tablespace test_space shrink space keep 2M;
drop tablespace test_space including contents and datafiles;
drop procedure proc_test_space;

CREATE TABLESPACE TEST_SPC_ALTER DATAFILE 'test_df_alter' size 200M;
ALTER DATABASE  DATAFILE 'test_df_alter' RESIZE 50M;
ALTER DATABASE  DATAFILE 'test_df_alter' RESIZE 300M;
