SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert RAISE 2;
SYNCPOINT SIGNAL start_insert RAISE 2;
SYNCPOINT SP_B4_HEAP_INSERT SIGNALx start_insert RAISE 2;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL SIGNAL RAISE 2;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert RAISEx 2;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert RAISE xx;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert RAISE 2 xx;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert;

SYNCPOINT SP_B4_HEAP_INSERT WAIT start_insert;
SYNCPOINT SP_B4_HEAP_INSERT WAITx start_insert;
SYNCPOINT SP_B4_HEAP_INSERT WAIT wait;
SYNCPOINT SP_B4_HEAP_INSERT WAIT start_insert xxx;

SYNCPOINT RESET;
SYNCPOINT RESETx;
SYNCPOINT RESET xxx;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert RAISE 2; SYNCPOINT SP_AFTER_HEAP_INSERT WAIT end_insert; SYNCPOINT SP_B4_HEAP_UPDATE WAIT xxx; SYNCPOINT SP_B4_HEAP_DELETE WAIT yyy;
