DROP TABLE IF EXISTS TEST_SYNCPOINT;
CREATE TABLE TEST_SYNCPOINT(id int);
INSERT INTO TEST_SYNCPOINT VALUES(1);
SYNCPOINT SP_B4_HEAP_DELETE SIGNAL del RAISE 1;
DELETE FROM TEST_SYNCPOINT;
COMMIT;
DROP TABLE TEST_SYNCPOINT;
