--DROP TABLE IF EXISTS TEST;
--CREATE TABLE TEST (ID INT);
BEGIN;
SYNCPOINT SP_B4_HEAP_INSERT SIGNAL start_insert RAISE 2;
SYNCPOINT SP_AFTER_HEAP_INSERT WAIT end_insert;
INSERT INTO TEST VALUES (1);
COMMIT;
