alter tablespace undo autoextend off;
drop table if exists undo_test1;
create table undo_test1(c1 int,c2 int, c3 varchar(256));
insert into undo_test1 values(1,1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
insert into undo_test1 values(1,1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
insert into undo_test1 values(1,1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
insert into undo_test1 values(1,1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
insert into undo_test1 values(1,1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
insert into undo_test1 select * from undo_test1;
drop table if exists undo_test1;
alter tablespace undo autoextend on next 16M;
