DROP FUNCTION IF EXISTS TEST_FUNC_1;
CREATE FUNCTION TEST_FUNC_1(A varchar)
RETURN varchar
AS
BEGIN
   RETURN SUBSTR(A,1,2);
END;
/

DROP FUNCTION IF EXISTS TEST_FUNC_2;
CREATE FUNCTION TEST_FUNC_2(A varchar)
RETURN varchar
AS
BEGIN
   if (TEST_FUNC_1(A) = 'ab') then
   	return A;
   else
   	return TEST_FUNC_1(A);
   end if; 
END;
/

SELECT TEST_FUNC_2('abc') from dual;
SELECT TEST_FUNC_2('aabc') from dual;


--BEGIN:TEST RETURN DATE
create or replace function string_to_datetime(date_str varchar2) 
return date as date_time date;
begin 
	date_time := to_date(date_str, 'YYYY-MM-DD"T"HH24:MI:SS'); 
	return date_time; 
end;
/

SELECT string_to_datetime('2018-01-01T01:01:01') FROM DUAL;
--END:TEST RETURN DATE


--test function name with quotes
--add 2018/07/10
--begin
--expect success
CREATE OR REPLACE FUNCTION get_bal(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no;
      RETURN(acc_bal);
    END get_bal;
/

--expect error
CREATE OR REPLACE FUNCTION "get_bal"(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no;
      RETURN(acc_bal);
    END get_bal;
/

--expect error
CREATE OR REPLACE FUNCTION "get_bal"(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no;
      RETURN(acc_bal);
    END "Get_bal";
/

--expect success
CREATE OR REPLACE FUNCTION "get_bal"(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no + 1;
      RETURN(acc_bal);
    END;
/

--expect success
CREATE OR REPLACE FUNCTION "get_bal"(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no + 1;
      RETURN(acc_bal);
    END "get_bal";
/

--expect success
CREATE OR REPLACE FUNCTION sys."get_bal"(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no + 1;
      RETURN(acc_bal);
    END "get_bal";
/

--test expect error:the self-recursive function appears in the DEFALUE expression of its own parameter
CREATE OR REPLACE FUNCTION test_func(p1 int, p2 integer default test_func(10)+abs(-10)) return integer 
IS
CURRENT_USER varchar(10);
BEGIN
 CURRENT_USER := 'cantian';
 dbe_output.print_line( 'results' || CURRENT_USER||':'||p2);
 RETURN p2;
END;
/
--test:the self-recursive function appears in the DEFALUE expression of its own parameter

--expect return 2
select "get_bal"(1) from dual;
--expect return 1
select get_bal(1) from dual;

drop function get_bal;
drop function "get_bal";

--expect success
CREATE OR REPLACE FUNCTION sys."get_bal"(acc_no IN NUMBER)
   RETURN NUMBER
   IS acc_bal NUMBER(11,2);
   BEGIN
      acc_bal := acc_no + 2;
      RETURN(acc_bal);
    END "get_bal";
/
--expect return 3
select "get_bal"(1) from dual;
--expect return 3
select sys."get_bal"(1) from dual;
drop function "get_bal";
--end test function name with quotes

DROP TABLE IF EXISTS UTILS_ERRLOG;
DROP TABLE IF EXISTS T_VTABSP_CHK_BTSOTHPARA_A42;
DROP TABLE IF EXISTS T_D_BTSOTHPARA_A4;

CREATE TABLE UTILS_ERRLOG
(
  IINDEX NUMBER(10) NOT NULL,
  VERSION VARCHAR(75 BYTE) NOT NULL,
  PLANID NUMBER(10) NOT NULL,
  CMENEID NUMBER(10) NOT NULL,
  MOID VARCHAR(383 BYTE) NOT NULL,
  MONAME VARCHAR(750 BYTE) NOT NULL,
  ERRINFO VARCHAR(3990 BYTE) NOT NULL,
  ERRPARA VARCHAR(1536 BYTE),
  ILEVEL NUMBER(10) NOT NULL DEFAULT 0,
  ERRLOCATION VARCHAR(383 BYTE),
  PRIMARY KEY(IINDEX)
);

INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(149,'A4',28,101,'CMENEID:101,CMERECORDID:1_23_0_0_0_36_6','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST2;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(148,'A4',28,101,'CMENEID:101,CMERECORDID:1_11_0_0_14_18_3','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST2;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(147,'A4',28,101,'CMENEID:101,CMERECORDID:1_0_0_0_0_0_0','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST2;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(146,'A4',28,101,'CMENEID:101,CMERECORDID:0_0_0_0_0_0_0','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST1;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(145,'A4',28,101,'CMENEID:101,BTSID:1','BTSAUTODLDACTINFO','BTSOM_BTSCM_SITE_BTSAUTODLDACTINFO_ADLDACT_OFF','TDM_TEST2;BTSAUTODLDACTINFO@ADLDACT;BTSAUTODLDACTINFO@ADVER1;BTSAUTODLDACTINFO@ADVER2;BTSAUTODLDACTINFO@PV;BTSAUTODLDACTINFO@ADMODE',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(144,'A4',28,101,'CMENEID:101,BTSID:0','BTSAUTODLDACTINFO','BTSOM_BTSCM_SITE_BTSAUTODLDACTINFO_ADLDACT_OFF','TDM_TEST1;BTSAUTODLDACTINFO@ADLDACT;BTSAUTODLDACTINFO@ADVER1;BTSAUTODLDACTINFO@ADVER2;BTSAUTODLDACTINFO@PV;BTSAUTODLDACTINFO@ADMODE',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(285,'A4',37,126,'CMENEID:126,CMERECORDID:1_23_0_0_0_36_6','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST2;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(284,'A4',37,126,'CMENEID:126,CMERECORDID:1_11_0_0_14_18_3','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST2;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(283,'A4',37,126,'CMENEID:126,CMERECORDID:1_0_0_0_0_0_0','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST2;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(282,'A4',37,126,'CMENEID:126,CMERECORDID:0_0_0_0_0_0_0','BTSCONNECT','CM_ERROR_NOSRAN30_BTS_SHOULD_NOT_INPUT_CN_SRN_SN','TDM_TEST1;BTSCONNECT@INCN;BTSCONNECT@INSRN;BTSCONNECT@INSN',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(281,'A4',37,126,'CMENEID:126,BTSID:1','BTSAUTODLDACTINFO','BTSOM_BTSCM_SITE_BTSAUTODLDACTINFO_ADLDACT_OFF','TDM_TEST2;BTSAUTODLDACTINFO@ADLDACT;BTSAUTODLDACTINFO@ADVER1;BTSAUTODLDACTINFO@ADVER2;BTSAUTODLDACTINFO@PV;BTSAUTODLDACTINFO@ADMODE',1,null);
INSERT INTO UTILS_ERRLOG (IINDEX,VERSION,PLANID,CMENEID,MOID,MONAME,ERRINFO,ERRPARA,ILEVEL,ERRLOCATION) values(280,'A4',37,126,'CMENEID:126,BTSID:0','BTSAUTODLDACTINFO','BTSOM_BTSCM_SITE_BTSAUTODLDACTINFO_ADLDACT_OFF','TDM_TEST1;BTSAUTODLDACTINFO@ADLDACT;BTSAUTODLDACTINFO@ADVER1;BTSAUTODLDACTINFO@ADVER2;BTSAUTODLDACTINFO@PV;BTSAUTODLDACTINFO@ADMODE',1,null);

CREATE GLOBAL TEMPORARY TABLE T_VTABSP_CHK_BTSOTHPARA_A42
(
  PLANID NUMBER(10) NOT NULL,
  CMENEID NUMBER(10) NOT NULL,
  BTSID NUMBER(10) NOT NULL,
  BTSTYPE NUMBER(10) NOT NULL,
  BTSNAME VARCHAR(150 BYTE) NOT NULL,
  ISSUPERBTS NUMBER(10),
  MAINDEVTAB VARCHAR(150 BYTE),
  BAKDEVTAB VARCHAR(150 BYTE)
);

CREATE TABLE T_D_BTSOTHPARA_A4
(
  SAVEPOINTID NUMBER(10) NOT NULL,
  OPERTYPE NUMBER(3) NOT NULL,
  PLANID NUMBER(10) NOT NULL,
  CMENEID NUMBER(10) NOT NULL,
  BTSID NUMBER(10) NOT NULL,
  SYNCMETHOD NUMBER(3),
  PSUTURNINGOFFENABLE NUMBER(3),
  BTSDETECTSWITCH NUMBER(3),
  PAADJVOL NUMBER(3),
  RESETTIME NUMBER(3),
  SENDSAMBE NUMBER(3),
  ISSUPERBTS NUMBER(3),
  JITBUFDELAY NUMBER(3),
  PROBESEQ NUMBER(3),
  PRIVATEPROBENUM NUMBER(3),
  PRIVATEPROBEFST NUMBER(3),
  PRIVATEPROBESND NUMBER(3),
  PDCHGBR NUMBER(3),
  MCPACUTPWRPRIPOLICY NUMBER(3),
  MCPACUTPSCUTPWRRANGE NUMBER(3),
  SPRTLU NUMBER(3),
  ABISIDLETSCFGSWITCH NUMBER(3),
  ABISIDLETSALLOC NUMBER(3),
  ENERGYMNG NUMBER(3),
  MTSTURNOFF NUMBER(3),
  SPRECM NUMBER(3),
  ECMP NUMBER(3),
  HIGHMODPWRSW NUMBER(3),
  BATIMS NUMBER(3),
  CPRIFASTRING NUMBER(3),
  SUPPORTE1UNBA NUMBER(3),
  E1BLNMD NUMBER(3),
  TSSHTDOWNEN NUMBER(3),
  VSWRTHRESOPT NUMBER(3),
  FASTTRXAIDSW NUMBER(3),
  STPPWRCHK NUMBER(3),
  AISSOP NUMBER(3),
  AISSFREQ NUMBER(3),
  AISSNETMODE NUMBER(3),
  E1PORTFAILDELAY NUMBER(3),
  E1PORTSTAQUICKREPSW NUMBER(3),
  VSWRDETECTSENENHSW NUMBER(3),
  PTRAUTSNSNEXTSW NUMBER(3),
  BTSDBUS32KCFGSW NUMBER(3),
  IPCLKSYNMODE NUMBER(3),
  SDBBLSD NUMBER(3),
  AMRTRANSBANDTHCOMPSW NUMBER(3),
  BTSSIGNALMSGCOMPSW NUMBER(3),
  ABISSIDSENDPERIOD NUMBER(3),
  ABISUSERFRAMEMUXDELAY NUMBER(3),
  OMLFAILROLLBACKPOLICY NUMBER(3),
  DUAPAPOWSHRCONFCHEOPTSW NUMBER(3),
  IWFVLANOPTSW NUMBER(3),
  NOTRAFFICSELFHEALSW NUMBER(3),
  RFUNITSTDETECTSW NUMBER(3),
  RFUNITSTDETECTREFRLALMSW NUMBER(3),
  RFUNITSTDETECTSNRTHRD NUMBER(3),
  RFUNITSTDETECTPNTHRD NUMBER(3),
  DRFURELAYDETECTSW NUMBER(3),
  BOARDRUNABNORMALOPTSW NUMBER(3),
  LOGUPTID VARCHAR(383 BYTE),
  NBI_RECID NUMBER(10),
  ISGENMML NUMBER(3),
  PRIMARY KEY(PLANID, CMENEID, BTSID, OPERTYPE, SAVEPOINTID)
);

INSERT INTO T_D_BTSOTHPARA_A4 (SAVEPOINTID,OPERTYPE,PLANID,CMENEID,BTSID,SYNCMETHOD,PSUTURNINGOFFENABLE,BTSDETECTSWITCH,PAADJVOL,RESETTIME,SENDSAMBE,ISSUPERBTS,JITBUFDELAY,PROBESEQ,PRIVATEPROBENUM,PRIVATEPROBEFST,PRIVATEPROBESND,PDCHGBR,MCPACUTPWRPRIPOLICY,MCPACUTPSCUTPWRRANGE,SPRTLU,ABISIDLETSCFGSWITCH,ABISIDLETSALLOC,ENERGYMNG,MTSTURNOFF,SPRECM,ECMP,HIGHMODPWRSW,BATIMS,CPRIFASTRING,SUPPORTE1UNBA,E1BLNMD,TSSHTDOWNEN,VSWRTHRESOPT,FASTTRXAIDSW,STPPWRCHK,AISSOP,AISSFREQ,AISSNETMODE,E1PORTFAILDELAY,E1PORTSTAQUICKREPSW,VSWRDETECTSENENHSW,PTRAUTSNSNEXTSW,BTSDBUS32KCFGSW,IPCLKSYNMODE,SDBBLSD,AMRTRANSBANDTHCOMPSW,BTSSIGNALMSGCOMPSW,ABISSIDSENDPERIOD,ABISUSERFRAMEMUXDELAY,OMLFAILROLLBACKPOLICY,DUAPAPOWSHRCONFCHEOPTSW,IWFVLANOPTSW,NOTRAFFICSELFHEALSW,RFUNITSTDETECTSW,RFUNITSTDETECTREFRLALMSW,RFUNITSTDETECTSNRTHRD,RFUNITSTDETECTPNTHRD,DRFURELAYDETECTSW,BOARDRUNABNORMALOPTSW,LOGUPTID,NBI_RECID,ISGENMML) values(0,2,35,116,0,0,0,0,null,15,1,null,2,255,null,null,null,0,0,null,0,0,0,0,255,1,0,0,0,0,0,null,0,1,0,0,0,null,null,0,0,0,null,null,null,null,0,null,null,null,0,0,null,1,0,null,null,null,0,1,null,508,0);
INSERT INTO T_D_BTSOTHPARA_A4 (SAVEPOINTID,OPERTYPE,PLANID,CMENEID,BTSID,SYNCMETHOD,PSUTURNINGOFFENABLE,BTSDETECTSWITCH,PAADJVOL,RESETTIME,SENDSAMBE,ISSUPERBTS,JITBUFDELAY,PROBESEQ,PRIVATEPROBENUM,PRIVATEPROBEFST,PRIVATEPROBESND,PDCHGBR,MCPACUTPWRPRIPOLICY,MCPACUTPSCUTPWRRANGE,SPRTLU,ABISIDLETSCFGSWITCH,ABISIDLETSALLOC,ENERGYMNG,MTSTURNOFF,SPRECM,ECMP,HIGHMODPWRSW,BATIMS,CPRIFASTRING,SUPPORTE1UNBA,E1BLNMD,TSSHTDOWNEN,VSWRTHRESOPT,FASTTRXAIDSW,STPPWRCHK,AISSOP,AISSFREQ,AISSNETMODE,E1PORTFAILDELAY,E1PORTSTAQUICKREPSW,VSWRDETECTSENENHSW,PTRAUTSNSNEXTSW,BTSDBUS32KCFGSW,IPCLKSYNMODE,SDBBLSD,AMRTRANSBANDTHCOMPSW,BTSSIGNALMSGCOMPSW,ABISSIDSENDPERIOD,ABISUSERFRAMEMUXDELAY,OMLFAILROLLBACKPOLICY,DUAPAPOWSHRCONFCHEOPTSW,IWFVLANOPTSW,NOTRAFFICSELFHEALSW,RFUNITSTDETECTSW,RFUNITSTDETECTREFRLALMSW,RFUNITSTDETECTSNRTHRD,RFUNITSTDETECTPNTHRD,DRFURELAYDETECTSW,BOARDRUNABNORMALOPTSW,LOGUPTID,NBI_RECID,ISGENMML) values(0,2,35,116,1,0,0,0,null,15,1,null,2,255,null,null,null,0,0,null,0,0,0,0,255,1,0,0,0,0,0,null,0,1,0,0,0,null,null,0,0,0,null,null,null,null,0,null,null,null,0,0,null,1,0,null,null,null,0,1,null,509,0);
INSERT INTO T_D_BTSOTHPARA_A4 (SAVEPOINTID,OPERTYPE,PLANID,CMENEID,BTSID,SYNCMETHOD,PSUTURNINGOFFENABLE,BTSDETECTSWITCH,PAADJVOL,RESETTIME,SENDSAMBE,ISSUPERBTS,JITBUFDELAY,PROBESEQ,PRIVATEPROBENUM,PRIVATEPROBEFST,PRIVATEPROBESND,PDCHGBR,MCPACUTPWRPRIPOLICY,MCPACUTPSCUTPWRRANGE,SPRTLU,ABISIDLETSCFGSWITCH,ABISIDLETSALLOC,ENERGYMNG,MTSTURNOFF,SPRECM,ECMP,HIGHMODPWRSW,BATIMS,CPRIFASTRING,SUPPORTE1UNBA,E1BLNMD,TSSHTDOWNEN,VSWRTHRESOPT,FASTTRXAIDSW,STPPWRCHK,AISSOP,AISSFREQ,AISSNETMODE,E1PORTFAILDELAY,E1PORTSTAQUICKREPSW,VSWRDETECTSENENHSW,PTRAUTSNSNEXTSW,BTSDBUS32KCFGSW,IPCLKSYNMODE,SDBBLSD,AMRTRANSBANDTHCOMPSW,BTSSIGNALMSGCOMPSW,ABISSIDSENDPERIOD,ABISUSERFRAMEMUXDELAY,OMLFAILROLLBACKPOLICY,DUAPAPOWSHRCONFCHEOPTSW,IWFVLANOPTSW,NOTRAFFICSELFHEALSW,RFUNITSTDETECTSW,RFUNITSTDETECTREFRLALMSW,RFUNITSTDETECTSNRTHRD,RFUNITSTDETECTPNTHRD,DRFURELAYDETECTSW,BOARDRUNABNORMALOPTSW,LOGUPTID,NBI_RECID,ISGENMML) values(0,2,37,126,1,0,0,0,null,15,1,null,2,255,null,null,null,0,0,null,0,0,0,0,255,1,0,0,0,0,0,null,0,1,0,0,0,null,null,0,0,0,null,null,null,null,0,null,null,null,0,0,null,1,0,null,null,null,0,1,null,509,0);
INSERT INTO T_D_BTSOTHPARA_A4 (SAVEPOINTID,OPERTYPE,PLANID,CMENEID,BTSID,SYNCMETHOD,PSUTURNINGOFFENABLE,BTSDETECTSWITCH,PAADJVOL,RESETTIME,SENDSAMBE,ISSUPERBTS,JITBUFDELAY,PROBESEQ,PRIVATEPROBENUM,PRIVATEPROBEFST,PRIVATEPROBESND,PDCHGBR,MCPACUTPWRPRIPOLICY,MCPACUTPSCUTPWRRANGE,SPRTLU,ABISIDLETSCFGSWITCH,ABISIDLETSALLOC,ENERGYMNG,MTSTURNOFF,SPRECM,ECMP,HIGHMODPWRSW,BATIMS,CPRIFASTRING,SUPPORTE1UNBA,E1BLNMD,TSSHTDOWNEN,VSWRTHRESOPT,FASTTRXAIDSW,STPPWRCHK,AISSOP,AISSFREQ,AISSNETMODE,E1PORTFAILDELAY,E1PORTSTAQUICKREPSW,VSWRDETECTSENENHSW,PTRAUTSNSNEXTSW,BTSDBUS32KCFGSW,IPCLKSYNMODE,SDBBLSD,AMRTRANSBANDTHCOMPSW,BTSSIGNALMSGCOMPSW,ABISSIDSENDPERIOD,ABISUSERFRAMEMUXDELAY,OMLFAILROLLBACKPOLICY,DUAPAPOWSHRCONFCHEOPTSW,IWFVLANOPTSW,NOTRAFFICSELFHEALSW,RFUNITSTDETECTSW,RFUNITSTDETECTREFRLALMSW,RFUNITSTDETECTSNRTHRD,RFUNITSTDETECTPNTHRD,DRFURELAYDETECTSW,BOARDRUNABNORMALOPTSW,LOGUPTID,NBI_RECID,ISGENMML) values(0,2,37,126,0,0,0,0,null,15,1,null,2,255,null,null,null,0,0,null,0,0,0,0,255,1,0,0,0,0,0,null,0,1,0,0,0,null,null,0,0,0,null,null,null,null,0,null,null,null,0,0,null,1,0,null,null,null,0,1,null,508,0);
INSERT INTO T_D_BTSOTHPARA_A4 (SAVEPOINTID,OPERTYPE,PLANID,CMENEID,BTSID,SYNCMETHOD,PSUTURNINGOFFENABLE,BTSDETECTSWITCH,PAADJVOL,RESETTIME,SENDSAMBE,ISSUPERBTS,JITBUFDELAY,PROBESEQ,PRIVATEPROBENUM,PRIVATEPROBEFST,PRIVATEPROBESND,PDCHGBR,MCPACUTPWRPRIPOLICY,MCPACUTPSCUTPWRRANGE,SPRTLU,ABISIDLETSCFGSWITCH,ABISIDLETSALLOC,ENERGYMNG,MTSTURNOFF,SPRECM,ECMP,HIGHMODPWRSW,BATIMS,CPRIFASTRING,SUPPORTE1UNBA,E1BLNMD,TSSHTDOWNEN,VSWRTHRESOPT,FASTTRXAIDSW,STPPWRCHK,AISSOP,AISSFREQ,AISSNETMODE,E1PORTFAILDELAY,E1PORTSTAQUICKREPSW,VSWRDETECTSENENHSW,PTRAUTSNSNEXTSW,BTSDBUS32KCFGSW,IPCLKSYNMODE,SDBBLSD,AMRTRANSBANDTHCOMPSW,BTSSIGNALMSGCOMPSW,ABISSIDSENDPERIOD,ABISUSERFRAMEMUXDELAY,OMLFAILROLLBACKPOLICY,DUAPAPOWSHRCONFCHEOPTSW,IWFVLANOPTSW,NOTRAFFICSELFHEALSW,RFUNITSTDETECTSW,RFUNITSTDETECTREFRLALMSW,RFUNITSTDETECTSNRTHRD,RFUNITSTDETECTPNTHRD,DRFURELAYDETECTSW,BOARDRUNABNORMALOPTSW,LOGUPTID,NBI_RECID,ISGENMML) values(0,2,36,121,0,0,0,0,null,15,1,null,2,255,null,null,null,0,0,null,0,0,0,0,255,1,0,0,0,0,0,null,0,1,0,0,0,null,null,0,0,0,null,null,null,null,0,null,null,null,0,0,null,1,0,null,null,null,0,1,null,508,0);
INSERT INTO T_D_BTSOTHPARA_A4 (SAVEPOINTID,OPERTYPE,PLANID,CMENEID,BTSID,SYNCMETHOD,PSUTURNINGOFFENABLE,BTSDETECTSWITCH,PAADJVOL,RESETTIME,SENDSAMBE,ISSUPERBTS,JITBUFDELAY,PROBESEQ,PRIVATEPROBENUM,PRIVATEPROBEFST,PRIVATEPROBESND,PDCHGBR,MCPACUTPWRPRIPOLICY,MCPACUTPSCUTPWRRANGE,SPRTLU,ABISIDLETSCFGSWITCH,ABISIDLETSALLOC,ENERGYMNG,MTSTURNOFF,SPRECM,ECMP,HIGHMODPWRSW,BATIMS,CPRIFASTRING,SUPPORTE1UNBA,E1BLNMD,TSSHTDOWNEN,VSWRTHRESOPT,FASTTRXAIDSW,STPPWRCHK,AISSOP,AISSFREQ,AISSNETMODE,E1PORTFAILDELAY,E1PORTSTAQUICKREPSW,VSWRDETECTSENENHSW,PTRAUTSNSNEXTSW,BTSDBUS32KCFGSW,IPCLKSYNMODE,SDBBLSD,AMRTRANSBANDTHCOMPSW,BTSSIGNALMSGCOMPSW,ABISSIDSENDPERIOD,ABISUSERFRAMEMUXDELAY,OMLFAILROLLBACKPOLICY,DUAPAPOWSHRCONFCHEOPTSW,IWFVLANOPTSW,NOTRAFFICSELFHEALSW,RFUNITSTDETECTSW,RFUNITSTDETECTREFRLALMSW,RFUNITSTDETECTSNRTHRD,RFUNITSTDETECTPNTHRD,DRFURELAYDETECTSW,BOARDRUNABNORMALOPTSW,LOGUPTID,NBI_RECID,ISGENMML) values(0,2,36,121,1,0,0,0,null,15,1,null,2,255,null,null,null,0,0,null,0,0,0,0,255,1,0,0,0,0,0,null,0,1,0,0,0,null,null,0,0,0,null,null,null,null,0,null,null,null,0,0,null,1,0,null,null,null,0,1,null,509,0);

CREATE or replace FUNCTION func_objectid(A NUMBER)
RETURN INT
AS
BEGIN
   if (A = 35) then
   	return A;
   else
   	return 0;
   end if; 
END;
/

INSERT INTO T_VTABSP_CHK_BTSOTHPARA_A42 (PLANID,CMENEID,BTSID,BTSTYPE,BTSNAME,ISSUPERBTS,MAINDEVTAB,BAKDEVTAB ) values(35,116,0,0,'zzz',0,'','');
select distinct 'A4' , a.PlanID , a.CMENEID , 'CMENEID:' as MoID , 'BTSOTHPARA' , 'GEN_CM_MML_SITE_MML_PTU_BARCODE_DUPLICATED' , b.BTSNAME || ';BTSESN@MAINDEVTAB;' || ';BTSESN@BAKDEVTAB'  from t_D_BTSOTHPARA_A4 a join t_vTabsp_Chk_BTSOTHPARA_A42 b on b.PlanID = a.PlanID and b.CMENEID = a.CMENEID and b.BTSID = a.BTSID where a.PlanID = 35 and a.OperType in (2 , 4 ) and func_objectid(b.PlanID) = 35;

DROP TABLE IF EXISTS USER_FUNC_TEMP;
CREATE TABLE USER_FUNC_TEMP(ID INT);
CREATE OR REPLACE FUNCTION USER_FUNC_CHG_TEMP(a INT) RETURN INT
AS c INT;
BEGIN
c := a; 
INSERT INTO USER_FUNC_TEMP VALUES (c);
return c;
END USER_FUNC_CHG_TEMP;
/
select USER_FUNC_CHG_TEMP(1) from dual;
drop table USER_FUNC_TEMP;
drop FUNCTION USER_FUNC_CHG_TEMP;

drop table if exists t_sub_query_101;
create table t_sub_query_101(id int,c_int int not null,c_vchar varchar(100) not null,c_clob clob not null,c_blob blob not null,c_date date);
CREATE OR REPLACE FUNCTION pro3(p2 integer ) return integer
IS
CURRENT_USER varchar(10);
BEGIN
CURRENT_USER := 'cantian';
dbe_output.print_line( 'results' || CURRENT_USER||':'||p2);
RETURN p2;
END;
/
select pro3((select c_int from t_sub_query_101 where id=1)) from dual;
