ALTER SYSTEM SET ENABLE_ERR_SUPERPOSED = TRUE;

SELECT * FROM SYS1111.ALL_VIEW_COLUMNS;
SELECT LTRIM(TYPE_ID2NAME('A')) FROM DUAL;
SELECT SLEEP(TYPE_ID2NAME('A')) FROM DUAL;
SELECT FROM_UNIXTIME(9223372036854775807);
SELECT FROM_UNIXTIME(-9223372036854775807);
SELECT FROM_UNIXTIME(9223372036854775809);
SELECT FROM_UNIXTIME(-9223372036854775809);
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH:MI:SS asx';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH:MI:SS.FF asx';

CREATE TABLE T_FORUPDATE_1 (F_INT1 INT, F_INT2 INT, F_CHAR CHAR(16), F_DATE DATE);
SELECT F_INT1 FROM T_FORUPDATE_1 FOR UPDATE UNION ALL SELECT F_INT1 FROM T_FORUPDATE_1;
SELECT F_INT1 FROM T_FORUPDATE_1 FOR UPDATE LIMIT 1;
UPDATE T_FORUPDATE_1 SET *=1;

DECLARE
    A INT;
    B CHAR(16);
    C VARCHAR(16);
BEGIN
    A := 10;
    B := 'ABC';
    C := 'EFC';
    EXECUTE IMMEDIATE 'BEGIN dbe_output.print_line(:X||:Y||:Z);END;' USING A,B;
END;
/

CREATE OR REPLACE PROCEDURE PROC_GETDATABYPAGE(V_SQLSTR IN VARCHAR2,
    V_PAGESIZE IN NUMBER,
    V_CURRENTPAGE IN NUMBER) AS
    V_REFCUR SYS_REFCURSOR;
    V_REFCUR2 SYS_REFCURSOR;
    V_FIRSTREC  NUMBER(10,0);
    V_LASTREC  NUMBER(10,0);
    V_DT  VARCHAR2(10);
    SWV_SQLSTR VARCHAR2(8000);
BEGIN
    BEGIN
    V_DT := SUBSTR(CAST(DBE_RANDOM.GET_STRING('U',3) AS VARCHAR2),3,10);
    dbe_output.print_line(V_DT);
    END;
END;
/

ALTER SYSTEM SET ENABLE_ERR_SUPERPOSED = FALSE;