--TEST insert ... select

--DTS2019012107224
drop table if exists INSERT_AAAA;
create table INSERT_AAAA(f1 int primary key, f2 varchar(20));
insert into INSERT_AAAA(f1,f2) values(1,'fddfsd;');
insert into INSERT_AAAA(f1,f2) values(2,'fdd;fsd');
insert into INSERT_AAAA(f1,f2) values(3,'fdd
fsd');
insert into INSERT_AAAA(f1,f2) values(4,'fddf
sd;');
insert into INSERT_AAAA(f1,f2) values(5,'fddfsd
;');
insert into INSERT_AAAA(f1,f2) values(6,'fdd
----;
sss');
insert into INSERT_AAAA(f1,f2) values(7,'fdd

xxx;  '  )  ;
select f2 from INSERT_AAAA order by f1;
insert into INSERT_AAAA(f1,f2) values(7,'fdd

xxx;  '  )  on duplicate key update f2='fdf
xxx

1111';
select f2 from INSERT_AAAA where f1=7;

drop table if exists test_temp_t1;
create table test_temp_t1(f1 int, f2 int);
insert into test_temp_t1(f1,f2) values(1,11);
insert into test_temp_t1(f1,f2) values(2,22);
commit;

drop table if exists test_temp_t2;
create table test_temp_t2(f1 int, f2 int);

insert into test_temp_t2 select * from test_temp_t1;
select * from test_temp_t2 order by f1 asc;
rollback;

insert into test_temp_t2(f1,f2) select * from test_temp_t1;
select * from test_temp_t2 order by f1 asc;
rollback;

insert into test_temp_t2(f2,f1) select * from test_temp_t1;
select * from test_temp_t2 order by f1 asc;
rollback;

insert into test_temp_t2 select f2,f1 from test_temp_t1;
select * from test_temp_t2 order by f1 asc;
rollback;

insert into test_temp_t2(f2,f1) (select f2,f1 from test_temp_t1);
select * from test_temp_t2 order by f1 asc;
rollback;

insert into test_temp_t2(f1) select f1 from test_temp_t1;
select * from test_temp_t2 order by f1 asc;
rollback;

drop table if exists test_temp_t3;
create table test_temp_t3(f1 char(10), f2 varchar(10));
insert into test_temp_t3(f1,f2) values('11', '22');
insert into test_temp_t2 select * from test_temp_t3;
commit;
select * from test_temp_t2 order by f1 asc;

insert into test_temp_t3(f1,f2) values('11aa', '22bb');
insert into test_temp_t2 select * from test_temp_t3;
commit;
select * from test_temp_t2 order by f1 asc;

insert into test_temp_t3(f1,f2) values('11', '22'),('22', '33'),('33', '44');

insert into test_temp_t1(f1, f2, f1) values(1,2,3);

drop table test_temp_t3;
drop table test_temp_t2;
drop table test_temp_t1;

DROP TABLE IF EXISTS T_INSERT_1;
CREATE TABLE T_INSERT_1(F1 INTEGER, F2 SERIAL PRIMARY KEY);
INSERT INTO T_INSERT_1 VALUES(NULL, NULL);
INSERT INTO T_INSERT_1(F1) VALUES(NULL);
INSERT INTO T_INSERT_1(F1) VALUES(NULL);
INSERT INTO T_INSERT_1(F1) VALUES(NULL);
INSERT INTO T_INSERT_1(F1) VALUES(NULL);
INSERT INTO T_INSERT_1(F1) VALUES(NULL);
COMMIT;
SELECT * FROM T_INSERT_1 ORDER BY F2;
DROP TABLE IF EXISTS T_INSERT_2;
CREATE TABLE T_INSERT_2(F1 INTEGER, F2 INTEGER NOT NULL);
INSERT INTO T_INSERT_2 VALUES(NULL, NULL);
COMMIT;
DROP TABLE T_INSERT_1;
DROP TABLE T_INSERT_2;

--DTS2018010914696 
DROP TABLE IF EXISTS T_INSERT_3;
CREATE TABLE T_INSERT_3(
ID INT,
C_SERIAL INT,
C_DOUBLE INT,
C_FLOAT FLOAT,
C_INT INT,
C_INTEGER INTEGER, C_BIGINT INT, C_REAL REAL, C_NUMERIC INT, C_NUMERIC_PARM INT, C_NUMBER INT,  C_NUMBER_PARM INT, C_DECIMAL DECIMAL, C_DECIMAL_PARM DECIMAL(5,2), C_BOOL CHAR(1),
C_CLOB VARCHAR(20), C_BLOB VARCHAR(20),
C_CHAR CHAR, C_CHAR1 CHAR(1), C_CHAR20 CHAR(20), C_CHAR4000 CHAR(400),
C_VARCHAR VARCHAR(20), C_VARCHAR1 VARCHAR(1), C_VARCHAR20 VARCHAR(20), C_VARCHAR4000 VARCHAR(4000),
C_VARCHAR2 VARCHAR(20), C_VARCHAR21 VARCHAR(1), C_VARCHAR220 VARCHAR(20), C_VARCHAR24000 VARCHAR(4000),
C_RAW VARCHAR(20), C_RAW1 VARCHAR(1), C_RAW20 VARCHAR(20), C_RAW4000 VARCHAR(4000),
C_BINARY VARCHAR(20), C_BINARY1 VARCHAR(1), C_BINARY20 VARCHAR(20), C_BINARY4000 VARCHAR(4000),
C_VARBINARY VARCHAR(20), C_VARBINARY1 VARCHAR(1), C_VARBINARY20 VARCHAR(20), C_VARBINARY4000 VARCHAR(4000),
C_DATE DATE, C_DATETIME DATE,
C_TIMESTAMP TIMESTAMP, C_TIMESTAMP3 TIMESTAMP(3), C_TIMESTAMP6 TIMESTAMP(6),
C_TIMESTAMP_WTZ TIMESTAMP WITH TIME ZONE, C_TIMESTAMP_WTZ3 TIMESTAMP(3) WITH TIME ZONE, C_TIMESTAMP_WTZ6 TIMESTAMP(6) WITH TIME ZONE,
C_INTERVAL VARCHAR(20),
C_BYTEA VARCHAR(20)
);

-- insert rows with length larger than 8000
INSERT INTO T_INSERT_3 VALUES( -554172411, -1727922176, 1494155264, 1.1, -1644429312, 733741056, 1650917376, -1717305344, -1141374976, 1827471360, -357040128, -1113063424, 7.7, 8.8, 'w', 'mtvycnfqdrskgb', 'imtvyc', 'b', 'n', 'bimtvycnfq', 
'ebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajb', 
'uebimtvycnfqd', 'p', 'luebimtv', 'sdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqsnusdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqsnudluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqsw',
'sdluebimtvycn', 'k', 'tsdl', 'zztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwg',
'zztsdluebimtvycnfqd', 'k', 'bzzts', 'zfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxd', 
'z', 'd', 'xzfbz', 'ajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrjxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiq', 
'a', 'i', 'majxzfbzztsdluebimtv', 'mdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsq',
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'md', 'fmdmajxzfb' );

INSERT INTO T_INSERT_3 VALUES( -3254235, -2342354, 2354, 1.1, -2452534, 2562354, 2354, -2542354, -1141374976, 2534, -2354, -35, 7.75, 8.8, 'w', 'mtvycnfqdrskgb', 'imtvyc', 'b', 'n', 'bimtvycnfq', 'ebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajb', 'uebimtvycnfqd', 'p', 'luebimtv', 'sdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqsnusdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqsnudluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqsw', 'sdluebimtvycn', 'k', 'tsdl', 
'zztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwg', 
'zztsdluebimtvycnfqd', 'k', 'bzzts', 'zfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxd', 
'z', 'd', 'xzfbz', 'ajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrjxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiq', 
'a', 'i', 'majxzfbzztsdluebimtv', 'mdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsq', 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'md', 'fmdmajxzfb' );

-- The following SQL will be refused in CTSQL client, since the maximal single line command can not exceed 4096 characters
INSERT INTO T_INSERT_3 VALUES( -554172412, -1727922176, 1494155264, 1.1, -1644429312, 733741056, 1650917376, -1717305344, -1141374976, 1827471360, -357040128, -1113063424, 7.7, 8.8, 'w', 'mtvycnfqdrskgb', 'imtvyc', 'b', 'n', 'bimtvycnfq', 'ebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajb', 'uebimtvycnfqd', 'p', 'luebimtv', 'sdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqsnusdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqsnudluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqsw', 'sdluebimtvycn', 'k', 'tsdl', 'zztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpjcqztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwg', 'zztsdluebimtvycnfqd', 'k', 'bzzts', 'zfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrihpfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxd', 'z', 'd', 'xzfbz', 'ajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmtxrjxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiq', 'a', 'i', 'majxzfbzztsdluebimtv', 'mdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsqwendqweklkqyxnpofuiaufhhbmmbzjlhqbqrsvucuspmrffitbdzzetoldoqfcmlrpxytazdyrwflaczjccltpxaimqvukvxlpdzhgebdwhuiiqbwgwyemmoltydvibmnzvvahvqnwvzskxfjixnmhdsbwkmmhabueopmrcdjgwdxnwertzicpcfpmoamuuzzqmtmnxhjtitbvntzegubjyfptwyhhptgxlmdmajxzfbzztsdluebimtvycnfqdrskgbwnqbskwispmigmletsrefwtgrdhqjjsprxkdlzoyowmemfovfwqjenpnhgzhpbpccxgszfmsqswhgujvnnlimosnliedschtqfhcwznmcajvvpduoodsvipalmnyrtgulyoacyebldejfehfhqsavtirtgwmbejlgzzbpzsconjmaqcwhbbhpumkxrbarlzgdgrecougnynybyjmfeoiyedyedmmytahcwoumttgkchpodlgxfvluzlafrfpgiidufrjbwgmgmsigbuemqcaqsuloqhjtpmgqeshtwadyktioolziytauxiihzoupnmloioyqwurghiyprhvnbnhqjliafgjmobdflujxdajbgxqmxtfgovhyybjyvfntiocezbfvuweiityinlulfnwzeabdejhdxhknpwekdsqhbhgvvhxpmuwphakyvwtvnwzixhloriasfsqecfpyrtpoeccruztispljicgtxuamtpnokdazctnuzgwiqrguyitjdmpcufwavevjmttvaeqijozuncbcmchnwmmekpeqcwxwqamqyjzqtxansliuikkfwycbsdvtuoiugiocikjtindqgfhmdlqmxbzmtheheammvawyksywyfqgabpgnbrammklgzjdaerslshyplvsgkgcmqhcfvnlagfzvjtqcmltwisfkepivwnumwfmvrmhkvpkqmrdjuawmurmbrscsjdmztgznwgaaexllrdllrkduridmtvjxghpsq', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'md', 'fmdmajxzfb' );
COMMIT;
DROP TABLE T_INSERT_3;


--
create user user_insert identified by 'Cantian_1234';
create table user_insert.user_insert_table1 (user_insert_table_f_int int);
create table user_insert.user_insert_table2 (user_insert_table_f_int int);
insert into user_insert.user_insert_table1 values(1);
select user_insert_table_f_int from user_insert.user_insert_table1;
select user_insert_table_f_int from user_insert.user_insert_table1,user_insert.user_insert_table2;
select user_insert.user_insert_table1.user_insert_table_f_int from user_insert.user_insert_table1,user_insert.user_insert_table1;
commit;
drop user user_insert cascade;

--DTS2018022303969
DROP TABLE IF EXISTS CAR;
create table CAR(CAR_ID number(6),CAR_CUST number(3),ADDR_3 number(5),CAR_CODE VARCHAR2(32),CAR_STATUS CHAR(1),CAR_REGION number(6),CAR_DOUBLE number(6,4),primary key (CAR_ID));
DROP TABLE IF EXISTS CAR_1;
create table CAR_1(CAR_ID number(6),CAR_CUST number(3),ADDR_3 number(5),CAR_CODE VARCHAR2(32),CAR_STATUS CHAR(1),CAR_REGION number(6),CAR_DOUBLE number(6,4),primary key (CAR_ID)); 
DROP TABLE IF EXISTS CAR_2;
create table CAR_2(CAR_ID number(6),CAR_CUST number(3),ADDR_3 number(5),CAR_CODE VARCHAR2(32),CAR_STATUS CHAR(1),CAR_REGION number(6),CAR_DOUBLE number(6,4),primary key (CAR_ID)); 
DROP TABLE IF EXISTS IPHONE;
create table IPHONE(PHONE_ID number(6),CUST number(3),ADDR_2 number(5),PHONE_CODE VARCHAR2(32),PHONE_STATUS CHAR(1),PHONE_REGION number(10),PHONE_DOUBLE number(20,4),primary key (PHONE_ID));
DROP TABLE IF EXISTS IPHONE1;
create table IPHONE1(PHONE_ID number(6),CUST number(3),ADDR_2 number(5),PHONE_CODE VARCHAR2(32),PHONE_STATUS CHAR(1),PHONE_REGION number(10),PHONE_DOUBLE number(20,4),primary key (PHONE_ID));
insert into car_1(car_id, car_cust, car_code, car_region) values(1,2,'Car_A1',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(2,3,'Car_A2',3);
insert into car_1(car_id, car_cust, car_code, car_region) values(3,4,'Car_A3',1);
insert into car_1(car_id, car_cust, car_code, car_region) values(4,5,'Car_A4',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(5,1,'Car_A5',3);
insert into car_1(car_id, car_cust, car_code, car_region) values(6,2,'Car_A6',1);
insert into car_1(car_id, car_cust, car_code, car_region) values(7,3,'Car_A7',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(8,4,'Car_A8',3);
insert into car_1(car_id, car_cust, car_code, car_region) values(9,5,'Car_A9',1);
insert into car_1(car_id, car_cust, car_code, car_region) values(10,1,'Car_A0',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(11,2,'Car_A1',3);
insert into car_1(car_id, car_cust, car_code, car_region) values(12,3,'Car_A2',1);
insert into car_1(car_id, car_cust, car_code, car_region) values(13,4,'Car_A3',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(14,5,'Car_A4',3);
insert into car_1(car_id, car_cust, car_code, car_region) values(15,1,'Car_A5',1);
insert into car_1(car_id, car_cust, car_code, car_region) values(16,2,'Car_A6',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(17,3,'Car_A7',3);
insert into car_1(car_id, car_cust, car_code, car_region) values(18,4,'Car_A8',1);
insert into car_1(car_id, car_cust, car_code, car_region) values(19,5,'Car_A9',2);
insert into car_1(car_id, car_cust, car_code, car_region) values(20,1,'Car_A0',3);

insert into car_2(car_id, car_cust, car_code, car_region) values(1,2,'Car_A1',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(2,3,'Car_A2',3);
insert into car_2(car_id, car_cust, car_code, car_region) values(3,4,'Car_A3',1);
insert into car_2(car_id, car_cust, car_code, car_region) values(4,5,'Car_A4',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(5,1,'Car_A5',3);
insert into car_2(car_id, car_cust, car_code, car_region) values(6,2,'Car_A6',1);
insert into car_2(car_id, car_cust, car_code, car_region) values(7,3,'Car_A7',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(8,4,'Car_A8',3);
insert into car_2(car_id, car_cust, car_code, car_region) values(9,5,'Car_A9',1);
insert into car_2(car_id, car_cust, car_code, car_region) values(10,1,'Car_A0',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(11,2,'Car_A1',3);
insert into car_2(car_id, car_cust, car_code, car_region) values(12,3,'Car_A2',1);
insert into car_2(car_id, car_cust, car_code, car_region) values(13,4,'Car_A3',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(14,5,'Car_A4',3);
insert into car_2(car_id, car_cust, car_code, car_region) values(15,1,'Car_A5',1);
insert into car_2(car_id, car_cust, car_code, car_region) values(16,2,'Car_A6',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(17,3,'Car_A7',3);
insert into car_2(car_id, car_cust, car_code, car_region) values(18,4,'Car_A8',1);
insert into car_2(car_id, car_cust, car_code, car_region) values(19,5,'Car_A9',2);
insert into car_2(car_id, car_cust, car_code, car_region) values(20,1,'Car_A0',3);

insert into iphone(phone_id, cust, phone_code, phone_region) values(1, 1, '13800000001', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(2, 2, '15800000002', 2);
insert into iphone(phone_id, cust, phone_code, phone_region) values(3, 3, '18800000003', 4);
insert into iphone(phone_id, cust, phone_code, phone_region) values(4, 4, '13800000004', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(5, 5, '15800000001', 2);
insert into iphone(phone_id, cust, phone_code, phone_region) values(6, 1, '18800000002', 3);
insert into iphone(phone_id, cust, phone_code, phone_region) values(7, 2, '13800000003', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(8, 3, '15800000004', 2);
insert into iphone(phone_id, cust, phone_code, phone_region) values(9, 4, '18800000001', 3);
insert into iphone(phone_id, cust, phone_code, phone_region) values(10, 5, '13800000002', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(11, 1, '15800000003', 2);
insert into iphone(phone_id, cust, phone_code, phone_region) values(12, 2, '18800000004', 3);
insert into iphone(phone_id, cust, phone_code, phone_region) values(13, 3, '13800000001', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(14, 4, '15800000002', 2);
insert into iphone(phone_id, cust, phone_code, phone_region) values(15, 5, '18800000003', 3);
insert into iphone(phone_id, cust, phone_code, phone_region) values(16, 1, '13800000004', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(17, 2, '15800000001', 2);
insert into iphone(phone_id, cust, phone_code, phone_region) values(18, 3, '18800000002', 3);
insert into iphone(phone_id, cust, phone_code, phone_region) values(19, 4, '13800000003', 1);
insert into iphone(phone_id, cust, phone_code, phone_region) values(20, 5, '15800000004', 2);

insert into iphone1(phone_id, cust, phone_code, phone_region) values(1, 1, '13800000001', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(2, 2, '15800000002', 2);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(3, 3, '18800000003', 3);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(4, 4, '13800000004', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(5, 5, '15800000001', 2);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(6, 1, '18800000002', 3);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(7, 2, '13800000003', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(8, 3, '15800000004', 2);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(9, 4, '18800000001', 3);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(10, 5, '13800000002', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(11, 1, '15800000003', 2);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(12, 2, '18800000004', 3);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(13, 3, '13800000001', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(14, 4, '15800000002', 2);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(15, 5, '18800000003', 3);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(16, 1, '13800000004', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(17, 2, '15800000001', 2);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(18, 3, '18800000002', 3);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(19, 4, '13800000003', 1);
insert into iphone1(phone_id, cust, phone_code, phone_region) values(20, 5, '15800000004', 2);
insert into car(car_id, car_cust, car_code, car_region) select (a.car_id+b.car_id) CID_XXX, a.car_cust, b.car_code, a.car_region+b.car_region AS CC_XXX from car_1 a inner join car_2 b on a.car_cust=b.car_cust where a.car_region=1 and b.car_region=3 and a.car_cust in(select c.cust from iphone c where c.phone_code = '13800000001') ;
select car_id, car_cust, car_code, car_region from car where 1=1 order by car_id;
DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS CAR_1;
DROP TABLE IF EXISTS CAR_2;
DROP TABLE IF EXISTS IPHONE;
DROP TABLE IF EXISTS IPHONE1;

--DTS2018032203200
DROP TABLE IF EXISTS nebula_xa_ddl_range_019;
create table nebula_xa_ddl_range_019(
c_id int,
c_d_id int NOT NULL,
c_w_id int NOT NULL,
c_first varchar(50) NOT NULL,
c_middle char(2),
c_last varchar(16) NOT NULL,
c_street_1 varchar(20) NOT NULL,
c_street_2 varchar(20),
c_city varchar(20) NOT NULL,
c_state char(2) NOT NULL,
c_zip char(9) NOT NULL,
c_phone char(16) NOT NULL,
c_since timestamp,
c_credit char(2) NOT NULL,
c_credit_lim numeric(12,2),
c_discount numeric(4,4),
c_balance numeric(12,2),
c_ytd_payment real NOT NULL,
c_payment_cnt number NOT NULL,
c_delivery_cnt bool NOT NULL,
c_end date NOT NULL,
c_data varchar(1000),
c_clob clob,
c_text blob) 
partition by range(c_id,c_first) 
(
partition PART_1 values less than (101,'is101'),
partition PART_2 values less than (201,'is201'),
partition PART_3 values less than (301,'is301'),
partition PART_4 values less than (401,'is401'),
partition PART_5 values less than (501,'is501'),
partition PART_6 values less than (601,'is601'),
partition PART_7 values less than (701,'is701'),
partition PART_8 values less than (801,'is801'),
partition PART_9 values less than (901,'is901'),
partition PART_10 values less than (maxvalue,maxvalue)
);

DROP TABLE IF EXISTS oracle_tbl_000;
create table oracle_tbl_000(
c_id int,
c_d_id int NOT NULL,
c_w_id int NOT NULL,
c_first varchar(50) NOT NULL,
c_middle char(2),
c_last varchar(16) NOT NULL,
c_street_1 varchar(20) NOT NULL,
c_street_2 varchar(20),
c_city varchar(20) NOT NULL,
c_state char(2) NOT NULL,
c_zip char(9) NOT NULL,
c_phone char(16) NOT NULL,
c_since timestamp,
c_credit char(2) NOT NULL,
c_credit_lim numeric(12,2),
c_discount numeric(4,4),
c_balance numeric(12,2),
c_ytd_payment real NOT NULL,
c_payment_cnt number NOT NULL,
c_delivery_cnt bool NOT NULL,
c_end date NOT NULL,
c_data varchar(1000),
c_clob clob,
c_text blob);
 
 
insert into oracle_tbl_000 values(1,1,1,'is'||'0'||'aaaaaabbbbbbc','OE','BAR'||'0'||'aa','bkili'||'1'||'fcrRGF'||'1','pmbwo'||'1'||'vhSDGJ'||'1','dyf'||'1'||'rDa'||'1','uq',4801||'1',940||'1'||215||'1',to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),'GC',50000.0,0.4361328,-10.0,10.0,1,true,to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),'QVLDETANRBRBURBMfhlhfrcllgfSMNTECC348493214893542NPFZCSfjlufvCDSFQVLDETANRBRBURBMfhlhfrcllgfSMNTECC348493214893542NPFZCSfjlufvCDSFQVLDETANRBRBURBMfhlhfrcllgfSMNTECC348493214893542NPFZCSfjlufvCDSFQVLDETANRBRBURBMfhlhfrcllgfSMNTECC348493214893542NPFZCSfjlufvCDSFQVLDETANRBRBURBMfhlhfrcllgfSMNTECC348493214893542NPFZCSfjlufvCDSFQVLDETANRBRBURBMfhlhfrcllgfSMNTECC348493214893542NPFZCSfjlufvCDSF'||'1','QVLDETANRBRBUflnfufscHOQNGGSMjjjjgfvmgfvdfcmkgvNPFZCSYKXXYSCDSFQVLDETANRBRBUflnfufscHOQNGGSMjjjjgfvmgfvdfcmkgvNPFZCSYKXXYSCDSFQVLDETANRBRBUflnfufscHOQNGGSMjjjjgfvmgfvdfcmkgvNPFZCSYKXXYSCDSFQVLDETANRBRBUflnfufscHOQNGGSMjjjjgfvmgfvdfcmkgvNPFZCSYKXXYSCDSFQVLDETANRBRBUflnfufscHOQNGGSMjjjjgfvmgfvdfcmkgvNPFZCSYKXXYSCDSFQVLDETANRBRBUflnfufscHOQNGGSMjjjjgfvmgfvdfcmkgvNPFZCSYKXXYSCDSF'||'1','1234354587643123455213445656723123424554566776763221132454566768767433242323445453565654542323');
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
alter table nebula_xa_ddl_range_019 drop column c_clob;
alter table nebula_xa_ddl_range_019 add c_clob clob default 'aaaaaaaaaaaaa';
insert into nebula_xa_ddl_range_019 select * from oracle_tbl_000;
DROP TABLE IF EXISTS nebula_xa_ddl_range_019;
DROP TABLE IF EXISTS oracle_tbl_000;

--- insert some values
drop table if exists t_insert1;
drop table if exists t_insert2;
drop table if exists t_insert3;
create table t_insert1(f1 serial primary key, f2 int);
create table t_insert2(f1 int, f2 int);
create table t_insert3(f1 int, f2 varchar(10))
PARTITION BY RANGE(f1)
(
 PARTITION p1 values less than(10),
 PARTITION p2 values less than(20),
 PARTITION p3 values less than(30),
 PARTITION p4 values less than(40)
);

insert into t_insert1(f2) values(1),;
insert into t_insert1(f2) values(1),(;
insert into t_insert1(f2) values(1),(2,3),(4);
insert into t_insert1(f2) values(1),(sysdate);

insert into t_insert1(f2) values(1),(2),(3);
commit;
select * from t_insert1 order by f1, f2;

insert into t_insert1 values(4,4),(5,5),(6,6);
commit;
select * from t_insert1 order by f1, f2;

insert into t_insert1(f1,f2) values(7,7),(8,8),(9,9);
commit;
select * from t_insert1 order by f1, f2;

insert into t_insert2 select * from t_insert1;
commit;
select * from t_insert2 order by f1, f2;

insert into t_insert2(f1,f2) select * from t_insert1;
commit;
select * from t_insert2 order by f1, f2;

insert into t_insert3 values(2,'p1'),(12,'p2'),(22,'p3'),(33,'p4');
commit;
select * from t_insert3 order by f1,f2;
insert into t_insert3 values(3,'p1'),(13,'p2'),(23,'p3'),(43,'p5');
commit;
select * from t_insert3 order by f1,f2;

update t_insert2 set f1=(1),(2);
update t_insert2 set (f1,f2)=(1,2);
update t_insert2 set f1=8;
commit;
select * from t_insert2 order by f1, f2;

drop table if exists t_insert4;
create table t_insert4(a1 varchar(8000),a2 varchar(8000),a3 varchar(8000),a4 varchar(8000),a5 varchar(8000),a6 varchar(8000),a7 varchar(8000),a8 varchar(8000),a9 varchar(8000));
insert into t_insert4 select lpad('QVBRfSCC3484942ZCSfjvCF',8000,'QVLDBURhlhfrc484ZCSfjF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF',4000,'QVLDfscHOQgfvmPFZDSF') from dual;

drop table if exists t_insert5;
create table t_insert5(f1 int);
insert into t_insert5(sys.t_insert5.f1) values(1);
insert into t_insert5(test.t_insert5.f1) values(1);
insert into t_insert5(sys.t_insert5.f2) values(1);
insert into t_insert5(sys.t2.f1) values(1);
insert into t_insert5(sys.t2.f2) values(1);
insert into t_insert5(sys."t_insert5".f1) values(1);
insert into t_insert5(t_insert5.f1) values(2);
insert into t_insert5("T_INSERT5".f1) values(3);
insert into t_insert5("t_insert5".f1) values(3);
insert into t_insert5(t2.f1) values(4);
insert into t_insert5(t_insert5.f2) values(4);

drop table if exists t_insert6;
create table t_insert6
(
 subscribersn number(38) not null,
 version number(38) not null,
 tombtime number(38) not null
);
alter table t_insert6 add constraint PK_usersubscribe_version primary key (subscribersn);
create index idx_usv_version on t_insert6 (version) ;

merge into t_insert6 c
using (select '8200000000' subscribersn, '20180601000000' version, '0' tombtime from dual) t 
on (c.subscribersn = t.subscribersn) 
when matched then update set c.version = t.version, c.tombtime = t.tombtime 
when not matched then insert (c.subscribersn, c.version, c.tombtime) values (t.subscribersn, t.version, t.tombtime);
select * from t_insert6;

drop table t_insert1;
drop table t_insert2;
drop table t_insert3;
drop table t_insert4;
drop table t_insert5;
drop table t_insert6;

--DTS2018092608118
DROP TABLE IF EXISTS TEST_LAST_INSERT_ID;
CREATE TABLE TEST_LAST_INSERT_ID(NAME VARCHAR(50),AGE INT,GENDER VARCHAR(50));
ALTER TABLE TEST_LAST_INSERT_ID ADD COLUMN ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
INSERT INTO TEST_LAST_INSERT_ID(NAME,AGE,GENDER) VALUES('JARY',23,'��');
COMMIT;
SELECT ID,NAME,AGE,GENDER FROM TEST_LAST_INSERT_ID ORDER BY ID,NAME,AGE,GENDER;
SELECT LAST_INSERT_ID();

--DTS2019053001343
drop table if exists ver_dml1;
create table ver_dml1(f1 int, f2 int, f3 int, f4 int);
drop table if exists ver_dml2;
create table ver_dml2 (f1 int, f2 int, f3 int, f4 int);

insert into ver_dml2 select * from ver_dml1 where ver_dml1.f1 = 1;
replace into ver_dml2 select * from ver_dml1 where ver_dml1.f1 = 1;
update ver_dml2 set f2 = '1' where f2 in (select f2 from ver_dml1);
delete from ver_dml2 where f2 in (select f2 from ver_dml1);
update ver_dml2 left join ver_dml1 on 1=1 set ver_dml2.f1 = '1' where ver_dml2.f2 in (select f2 from ver_dml1);
delete from ver_dml2 using ver_dml1 join ver_dml2 on 1=1 where ver_dml2.f2 in (select f2 from ver_dml1);

insert into sys_comments select * from ver_dml1;
replace into sys_comments select * from ver_dml1;
insert into sys_comments select * from sys_comments where table#='1111';
replace into sys_comments select * from ver_dml1;
update sys_comments set text = '1' where text in (select f2 from ver_dml1);
delete from sys_comments where text in (select f2 from ver_dml1);
update sys_comments left join ver_dml1 on 1=1 set sys_comments.text = '1' where sys_comments.text in (select f2 from ver_dml1);
delete from sys_comments using ver_dml1 join sys_comments on 1=1 where sys_comments.text in (select f2 from ver_dml1);

insert into SYS_USERS select * from ver_dml1;
replace into SYS_USERS select * from ver_dml1;
insert into SYS_USERS select * from SYS_USERS where table#='1111';
replace into SYS_USERS select * from SYS_USERS where table#='1111';
update SYS_USERS set NAME = '1' where NAME in (select f2 from ver_dml1);
delete from SYS_USERS where NAME in (select f2 from ver_dml1);
update SYS_USERS left join ver_dml1 on 1=1 set SYS_USERS.NAME = '1' where SYS_USERS.NAME in (select f2 from ver_dml1);
delete from SYS_USERS using ver_dml1 join SYS_USERS on 1=1 where SYS_USERS.id in (select f2 from ver_dml1);

drop table if exists ver_dml1;
drop table if exists ver_dml2;

--DTS2019061813474 DTS2019061814265
drop table if exists ver_dml1;
drop table if exists ver_dml2;
create table ver_dml1 (f1 int, f2 int);
create table ver_dml2 (f1 int, f2 int);
insert into ver_dml1 values (1,1),(2,2);
insert into ver_dml2 values (1,3);
drop view if exists ver_dml2_view;
create view ver_dml2_view as select * from ver_dml2;
select * from ver_dml1 order by f1;
select * from ver_dml2_view order by f1;
update ver_dml1 inner join ver_dml2_view on ver_dml1.f1=ver_dml2_view.f1 set ver_dml1.f2=5;
select * from ver_dml1 order by f1;
select * from ver_dml2_view order by f1;
update ver_dml1 inner join ver_dml2_view on ver_dml1.f1=ver_dml2_view.f1 set ver_dml2_view.f2=6;
delete ver_dml1 from ver_dml1 inner join ver_dml2_view on ver_dml1.f1=ver_dml2_view.f1;
select * from ver_dml1 order by f1;
select * from ver_dml2_view order by f1;
delete ver_dml2_view from ver_dml1 inner join ver_dml2_view on ver_dml1.f1=ver_dml2_view.f1;
MERGE INTO ver_dml1 BD1 USING ver_dml2_view NBD1 ON (BD1.f1 = NBD1.f1) WHEN MATCHED THEN UPDATE SET BD1.f2 = 10 WHEN NOT MATCHED THEN INSERT (f1, f2) VALUES (5,5);
select * from ver_dml1 order by f1;
select * from ver_dml2_view order by f1;
drop table if exists ver_dml1;
drop table if exists ver_dml2;
drop view if exists ver_dml2_view;

drop sequence if exists MY_DEPENDENCIES_011_Seq_01;
create sequence MY_DEPENDENCIES_011_Seq_01  increment by 2 start with 1 maxvalue 50 cache 10 cycle noorder;
drop table if exists MY_DEPENDENCIES_011_Tab_01;
create table  MY_DEPENDENCIES_011_Tab_01(id  int,name varchar(100),ctime date);
insert into MY_DEPENDENCIES_011_Tab_01 values (MY_DEPENDENCIES_011_Seq_01.nextval,'test','2018-09-17 16:10:28');
commit;
drop public synonym if exists MY_DEPENDENCIES_011_Syn_01;
create public synonym MY_DEPENDENCIES_011_Syn_01 for MY_DEPENDENCIES_011_Tab_01;
insert into MY_DEPENDENCIES_011_Syn_01 values (MY_DEPENDENCIES_011_Seq_01.nextval,'','2018-09-18 16:10:28');
commit;
select * from MY_DEPENDENCIES_011_Tab_01 order by id;
select * from MY_DEPENDENCIES_011_Syn_01 order by id;
drop sequence if exists MY_DEPENDENCIES_011_Seq_01;
drop public synonym if exists MY_DEPENDENCIES_011_Syn_01;
drop table if exists MY_DEPENDENCIES_011_Tab_01;

drop sequence if exists DBA_DEPENDENCIES_007_Seq_01;
drop sequence if exists DBA_DEPENDENCIES_008_Seq_01;
drop table if exists DBA_DEPENDENCIES_007_Tab_01;
drop table if exists DBA_DEPENDENCIES_008_Tab_01;
drop public synonym if exists DBA_DEPENDENCIES_007_Syn_01;
drop public synonym if exists DBA_DEPENDENCIES_008_Syn_01;
create sequence DBA_DEPENDENCIES_007_Seq_01  increment by 2 start with 1 maxvalue 50 cache 10 cycle noorder;
create table  DBA_DEPENDENCIES_007_Tab_01(id  int,name varchar(100),ctime date);
insert into DBA_DEPENDENCIES_007_Tab_01 values (DBA_DEPENDENCIES_007_Seq_01.nextval,'test','2018-09-17 16:10:28');
commit;
create public synonym DBA_DEPENDENCIES_007_Syn_01 for DBA_DEPENDENCIES_007_Tab_01;
drop function if exists DBA_DEPENDENCIES_007_Func_01;
create or replace function DBA_DEPENDENCIES_007_Func_01 return varchar
is
A varchar(30);
begin
insert into DBA_DEPENDENCIES_007_Syn_01 values (DBA_DEPENDENCIES_007_Seq_01.nextval,'zhongwen','2018-09-18 16:10:28');
select id into A  from DBA_DEPENDENCIES_007_Syn_01 where id = DBA_DEPENDENCIES_007_Seq_01.currval;
return A;
end;
/
select STATUS  from sys_procs where name = 'DBA_DEPENDENCIES_007_FUNC_01';
select * from dba_dependencies where name ='DBA_DEPENDENCIES_007_FUNC_01'  order by REFERENCED_OWNER,REFERENCED_TYPE;
--in pl refactor, we changed strategy: only when compile successfully can we update the table of dependency
create or replace function DBA_DEPENDENCIES_007_Func_01 return varchar
is
A varchar(30);
begin
insert into DBA_DEPENDENCIES_007_Syn_01 values (DBA_DEPENDENCIES_007_Seq_01.nextval,'zhongwen','2018-09-18 16:10:28');
return A;
end;
/
select STATUS  from sys_procs where name = 'DBA_DEPENDENCIES_007_FUNC_01';
select * from dba_dependencies where name ='DBA_DEPENDENCIES_007_FUNC_01'  order by REFERENCED_OWNER,REFERENCED_TYPE;
create sequence DBA_DEPENDENCIES_008_Seq_01  increment by 2 start with 1 maxvalue 50 cache 10 cycle noorder;
create table  DBA_DEPENDENCIES_008_Tab_01(id  int,name varchar(100),ctime date);
insert into DBA_DEPENDENCIES_008_Tab_01 values (DBA_DEPENDENCIES_008_Seq_01.nextval,'test','2018-09-17 16:10:28');
create public synonym DBA_DEPENDENCIES_008_Syn_01 for DBA_DEPENDENCIES_008_Tab_01;
commit;
insert into DBA_DEPENDENCIES_008_Syn_01 values (DBA_DEPENDENCIES_008_Seq_01.nextval,'zhongwen','2018-09-18 16:10:28');
commit;
drop function if exists DBA_DEPENDENCIES_007_Func_01;
drop sequence if exists DBA_DEPENDENCIES_007_Seq_01;
drop sequence if exists DBA_DEPENDENCIES_008_Seq_01;
drop public synonym if exists DBA_DEPENDENCIES_007_Syn_01;
drop public synonym if exists DBA_DEPENDENCIES_008_Syn_01;
drop table if exists DBA_DEPENDENCIES_007_Tab_01;
drop table if exists DBA_DEPENDENCIES_008_Tab_01;

--DTS2020022811308
DROP TABLE IF EXISTS "T_AGT_EXAMEXCUTELOG" CASCADE CONSTRAINTS;
CREATE TABLE "T_AGT_EXAMEXCUTELOG"
(
  "LOGID" VARCHAR(20 BYTE) NOT NULL,
  "EXAMPLANID" VARCHAR(20 BYTE),
  "PAPERID" VARCHAR(20 BYTE) NOT NULL,
  "STAFFID" VARCHAR(20 BYTE) NOT NULL,
  "STAFFNO" VARCHAR(20 BYTE),
  "SEQUENCE" NUMBER(10),
  "STARTTIME" DATE NOT NULL,
  "ENDTIME" DATE NOT NULL,
  "TIMELONG" NUMBER(10),
  "TESTISOVER" VARCHAR(1 BYTE) DEFAULT '0',
  "TESTMARK" NUMBER(7, 1),
  "LOGONIP" VARCHAR(20 BYTE),
  "ISPASSED" VARCHAR(1 BYTE),
  "MARKSTATUS" VARCHAR(1 BYTE),
  "MARKPERSON" VARCHAR(20 BYTE),
  "MARKPERSONNO" VARCHAR(20 BYTE),
  "RECHECKPERSON" VARCHAR(20 BYTE),
  "RECHECKPERSONNO" VARCHAR(20 BYTE),
  "ISCONTAINSUBJECT" VARCHAR(1 BYTE),
  "LOCKS" VARCHAR(1 BYTE),
  "EXCEPTIONCOUNT" NUMBER(5) DEFAULT 0,
  "FIELD1" VARCHAR(200 BYTE),
  "FIELD2" VARCHAR(200 BYTE),
  "FIELD3" VARCHAR(200 BYTE),
  "FIELD4" VARCHAR(200 BYTE),
  "FIELD5" VARCHAR(200 BYTE),
  "DELETEFLAG" VARCHAR(1 BYTE) DEFAULT '0'
)
PARTITION BY RANGE ("LOGID")
(
    PARTITION P_16_10_3 VALUES LESS THAN ('20161101')  INITRANS 2 PCTFREE 8,
    PARTITION P_16_11_1 VALUES LESS THAN ('20161111')  INITRANS 2 PCTFREE 8,
    PARTITION P_16_11_2 VALUES LESS THAN ('20161121')  INITRANS 2 PCTFREE 8,
    PARTITION P_16_11_3 VALUES LESS THAN ('20161201')  INITRANS 2 PCTFREE 8,
    PARTITION P_16_12_1 VALUES LESS THAN ('20161211')  INITRANS 2 PCTFREE 8,
    PARTITION P_16_12_2 VALUES LESS THAN ('20161221')  INITRANS 2 PCTFREE 8,
    PARTITION P_16_12_3 VALUES LESS THAN ('20170101')  INITRANS 2 PCTFREE 8,
    PARTITION P_MAX_VALUE VALUES LESS THAN (MAXVALUE )  INITRANS 2 PCTFREE 8
)
INITRANS 2
MAXTRANS 255
PCTFREE 8;
CREATE INDEX "IX_AGT_EXAMEXCUTELOG_EPLANID" ON "T_AGT_EXAMEXCUTELOG"("EXAMPLANID")
LOCAL
INITRANS 2
PCTFREE 8;
CREATE INDEX "IX_AGT_EXAMEXCUTELOG_PAPERID" ON "T_AGT_EXAMEXCUTELOG"("PAPERID")
LOCAL
INITRANS 2
PCTFREE 8;
CREATE INDEX "IX_AGT_EXAMEXCUTELOG_STAFFID" ON "T_AGT_EXAMEXCUTELOG"("STAFFID")
LOCAL
INITRANS 2
PCTFREE 8;
ALTER TABLE "T_AGT_EXAMEXCUTELOG" ADD CONSTRAINT "PK_T_AGT_EXAMEXCUTELOG" PRIMARY KEY("LOGID") USING INDEX LOCAL;
insert into T_AGT_EXAMEXCUTELOG values('1','2','3','4','5',6,'2016-01-01 00:00:00','2016-01-01 00:00:00',9,'0',11,'2','3','4','5','2','3','4','5','2',3,'4','5','2','3','4','5');
call dbe_stats.collect_table_stats( schema=>'SYS', name=>'T_AGT_EXAMEXCUTELOG', sample_ratio => 100, method_opt=>'for all columns');
DROP TABLE IF EXISTS DTS_TEST_T;
CREATE TABLE DTS_TEST_T(F1 CHAR(1));
insert into DTS_TEST_T values(decode(1,1,(SELECT ELOG.ISPASSED FROM T_AGT_EXAMEXCUTELOG ELOG WHERE ELOG.EXAMPLANID = 1  AND ELOG.STAFFID = 2  AND ELOG.DELETEFLAG <> '1' AND ELOG.SEQUENCE = 3),'0'));

-- DTS2020041614625
drop table if exists insert_on_error1;
drop table if exists insert_on_error2;
drop table if exists insert_on_error3;

create table insert_on_error1
(
  col1 int
);

create table insert_on_error2
(
  col1 int,
  col2 int,
  col3 varchar(20)
);

create table insert_on_error3
(
  col1 int,
  col2 int,
  col3 varchar(20)
);

insert into insert_on_error1 values(
  case when exists(
    select
      case when exists(
        select 
          t1.col1 as c1,
          t2.col1 as c2,
          t3.col1 as c3
        from insert_on_error2 as t3
        where 0 limit 1) 
      then t2.col1 else t2.col1 end
      as c1,
      t2.col2 as c2
    from insert_on_error1 as t0
      inner join insert_on_error2 as t1
      inner join insert_on_error2 as t2 on t2.col3 is not null
      on (1)
    ) then 1 else 2 end
);

insert into insert_on_error1 values(
  case when exists(
    select
      case when exists(
        select 
          t1.col1 as c1,
          t2.col1 as c2,
          t3.col1 as c3
        from insert_on_error2 as t3
        where 0 limit 1) 
      then t2.col1 else t2.col1 end
      as c1,
      t2.col2 as c2
    from insert_on_error1 as t0
      inner join insert_on_error2 as t1
      inner join insert_on_error2 as t2 on t2.col3 is not null
      on duplicate key update
    ) then 1 else 2 end
);

insert into insert_on_error2 (select * from insert_on_error3 on DUPLICATE KEY UPDATE col1 = col1*10);

drop table insert_on_error1;
drop table insert_on_error2;
drop table insert_on_error3;

--DTS202008240IRYM9P1100
DROP TABLE IF EXISTS  test_inset_upd_0;
DROP sequence IF EXISTS  cascade_standby_seq_000;
DROP sequence IF EXISTS  cascade_standby_seq_000_1;
CREATE TABLE  test_inset_upd_0 ( c_id INT,c_d_id BIGINT NOT NULL,c_w_id TINYINT unsigned NOT NULL,c_uint UINT NOT NULL,c_first VARCHAR(16) NOT NULL,c_middle CHAR(2),c_last VARCHAR(16) NOT NULL,c_street_1 VARCHAR(20) NOT NULL,c_street_2 VARCHAR(20),c_zero TIMESTAMP NOT NULL,c_start DATE NOT NULL,c_zip CHAR(9) NOT NULL,c_phone CHAR(16) NOT NULL,c_since TIMESTAMP,c_credit CHAR(2),c_credit_lim NUMERIC,c_discount NUMERIC(5, 2),c_balance NUMERIC(12, 2),c_ytd_payment REAL NOT NULL,c_payment_cnt number NOT NULL,c_delivery_cnt bool NOT NULL,c_end DATE NOT NULL,c_data1 VARCHAR(7744),c_data2 VARCHAR(7744),c_data3 VARCHAR(7744),c_data4 VARCHAR(7744),c_data5 VARCHAR(7744),c_data6 VARCHAR(7744),c_data7 VARCHAR(7744),c_data8 VARCHAR(7744),c_clob clob,c_blob blob);
CREATE sequence  cascade_standby_seq_000 start WITH 1 MAXVALUE 10 increment BY 1 CACHE 2 cycle;
CREATE sequence  cascade_standby_seq_000_1 start WITH 1 MAXVALUE 100 increment BY 1 CACHE 2 cycle;
INSERT INTO  test_inset_upd_0 (C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
    SELECT 0,0,0,0,'iscmRDs','OE','BARBar','RGF','SDG','2017-12-31 10:51:47','2017-12-31 10:51:47','4801','940215','2017-12-31 10:51:47','GC',50000.0,0.4361328,- 10.0,10.0,1,true,'2017-12-31 10:51:47',lpad('QVBRfSCC3484942ZCSfjvCF', 500, 'QVLDBURhlhfrc484ZCSfjF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 500, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 500, '1435764ABC7890abcdef');

CREATE or replace procedure  alter_table_range_proc(startall int,endall int) as
    i INT;
    j int;
    k int;
BEGIN
    FOR i IN startall..endall LOOP
        if i%8=1 then
            select  cascade_standby_seq_000.nextval into j from sys_dummy;
            if i%40=1 then
                select  cascade_standby_seq_000_1.nextval into k from sys_dummy;
                commit;
            end if;
            insert into   test_inset_upd_0 ( C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 2000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 2000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 1000, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 1000, '1435764ABC7890abcdef') FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 2 then
            INSERT INTO  test_inset_upd_0 (C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 3000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 3000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 5000, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 5000, '1435764ABC7890abcdef') FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 3 then
            INSERT INTO  test_inset_upd_0 (C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 3000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 3000, 'QVLDfscHOQgfvmPFZDSF'),NULL,NULL FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 4 then
            INSERT INTO  test_inset_upd_0 (C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 2000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 2000, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 2000, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 5000, '1435764ABC7890abcdef') FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 5 then
            INSERT INTO  test_inset_upd_0 ( C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 100, '1435764ABC7890abcdef') FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 6 then
            INSERT INTO  test_inset_upd_0 ( C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 5000, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 5000, '1435764ABC7890abcdef') FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 7 then
            INSERT INTO  test_inset_upd_0 (C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),NULL,NULL FROM  test_inset_upd_0 WHERE c_id = 0;
        elsif i % 8 = 0 then
            INSERT INTO  test_inset_upd_0 (C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB)
                SELECT i,i % 80,j,k,'iscmRDs' || i || 'aa',C_MIDDLE,'BARBar' || (i % 80) || 'xx','RGF' || j || 'AB','RGF' || k || 'ABC',C_ZERO + i,C_START + (i % 80),C_ZIP,C_PHONE,C_SINCE + j,C_CREDIT,i || '.' || i,i % 80,j,C_YTD_PAYMENT,k,C_DELIVERY_CNT,C_END + k,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('QVBUflcHOQNvmgfvdPFZSF', 100, 'QVLDfscHOQgfvmPFZDSF'),lpad('12314315487569809', 5000, '1435764ABC7890abcdef') FROM  test_inset_upd_0 WHERE c_id = 0;
        END IF;
    END LOOP;
END;
/

call  alter_table_range_proc(1, 10);
DELETE FROM  test_inset_upd_0 WHERE c_id = 0;
COMMIT;

SELECT count(*) FROM  test_inset_upd_0;

DROP TABLE IF EXISTS  test_inset_upd_1;
CREATE TABLE  test_inset_upd_1 (c_id INT,c_d_id BIGINT NOT NULL,c_w_id TINYINT unsigned NOT NULL,c_uint UINT NOT NULL,c_first VARCHAR(16) NOT NULL,c_middle CHAR(2),c_last VARCHAR(16) NOT NULL,c_street_1 VARCHAR(20) NOT NULL,c_street_2 VARCHAR(20),c_zero TIMESTAMP NOT NULL,c_start DATE NOT NULL,c_zip CHAR(9) NOT NULL,c_phone CHAR(16) NOT NULL,c_since TIMESTAMP,c_credit CHAR(2),c_credit_lim NUMERIC,c_discount NUMERIC(5, 2),c_balance NUMERIC(12, 2),c_ytd_payment REAL NOT NULL,c_payment_cnt number NOT NULL,c_delivery_cnt bool NOT NULL,c_end DATE NOT NULL,c_data1 VARCHAR(7744),c_data2 VARCHAR(7744),c_data3 VARCHAR(7744),c_data4 VARCHAR(7744),c_data5 VARCHAR(7744),c_data6 VARCHAR(7744),c_data7 VARCHAR(7744),c_data8 VARCHAR(7744),c_clob clob,c_blob blob) PARTITION BY range (c_id) SUBPARTITION BY range (c_d_id) (
    PARTITION part_1 VALUES less than(161) (SUBPARTITION P11 VALUES LESS THAN (17),SUBPARTITION P12 VALUES LESS THAN (33),SUBPARTITION P13 VALUES LESS THAN (49),SUBPARTITION P14 VALUES LESS THAN (MAXVALUE)),
    PARTITION part_2 VALUES less than(321) (SUBPARTITION P21 VALUES LESS THAN (17),SUBPARTITION P22 VALUES LESS THAN (33),SUBPARTITION P23 VALUES LESS THAN (49),SUBPARTITION P24 VALUES LESS THAN (MAXVALUE)));
INSERT IGNORE INTO  test_inset_upd_1(C_ID, C_D_ID, C_W_ID, C_UINT, C_FIRST, C_MIDDLE, C_LAST, C_STREET_1, C_STREET_2, C_ZERO, C_START, C_ZIP, C_PHONE, C_SINCE, C_CREDIT, C_CREDIT_LIM, C_DISCOUNT, C_BALANCE, C_YTD_PAYMENT, C_PAYMENT_CNT, C_DELIVERY_CNT, C_END, C_DATA1, C_DATA2, C_DATA3, C_DATA4, C_DATA5, C_DATA6, C_DATA7, C_DATA8, C_CLOB, C_BLOB)
SELECT C_ID,C_D_ID,C_W_ID,C_UINT,C_FIRST,C_MIDDLE,C_LAST,C_STREET_1,C_STREET_2,C_ZERO,C_START,C_ZIP,C_PHONE,C_SINCE,C_CREDIT,C_CREDIT_LIM,C_DISCOUNT,C_BALANCE,C_YTD_PAYMENT,C_PAYMENT_CNT,C_DELIVERY_CNT,C_END,C_DATA1,C_DATA2,C_DATA3,C_DATA4,C_DATA5,C_DATA6,C_DATA7,C_DATA8,C_CLOB,C_BLOB FROM  test_inset_upd_0;
COMMIT;

ALTER TABLE  test_inset_upd_1 ADD CONSTRAINT test_inset_upd_1_CONSTRAINT1 PRIMARY KEY ( c_phone,c_credit,c_credit_lim,c_zip,c_id );
insert into  test_inset_upd_1 select * from  test_inset_upd_0 ON DUPLICATE KEY UPDATE c_phone=C_FIRST,c_credit=c_credit,c_credit_lim=c_credit_lim,c_id=c_id;

DROP TABLE IF EXISTS  test_inset_upd_0;
DROP sequence IF EXISTS  cascade_standby_seq_000;
DROP sequence IF EXISTS  cascade_standby_seq_000_1;
DROP TABLE IF EXISTS  test_inset_upd_1;

-- DTS202011280VWZ1PP1J00
alter system set EMPTY_STRING_AS_NULL = FALSE;
drop table if exists test_default_empty_str;
create table test_default_empty_str(c int primary key, c1 varchar(10) default '');
replace into test_default_empty_str (c)values(123);
alter system set EMPTY_STRING_AS_NULL = TRUE;
drop table test_default_empty_str;

-- DTS202101190NRUPZP1D00
drop table if exists test_auto_inc;
create table test_auto_inc(f1 varchar(10), f2 int auto_increment primary key);
insert into test_auto_inc values(1, 2147483647);
alter table test_auto_inc drop f2;
insert into test_auto_inc(f1) values(2);
drop table test_auto_inc;
