SELECT ID FROM V$SESSION;
ALTER SYSTEM KILL SESSION -1;
ALTER SYSTEM KILL SESSION 0;
ALTER SYSTEM KILL SESSION 32;
--ACTIVE_ID SESSION must execute with kill session concurrently 
ALTER SYSTEM KILL SESSION ACTIVE_ID;