--DTS2019041106854
drop user if exists a cascade;
create user A identified by data_123;
grant dba to A;
conn a/data_123@127.0.0.1:1611
DROP TABLE IF EXISTS posts;
CREATE TABLE posts(post_id CHAR(2) NOT NULL, post_name CHAR(6) PRIMARY KEY, basic_wage INT,basic_bonus INT);
CREATE INDEX idx_posts ON posts(post_id ASC, post_name);
ALTER INDEX idx_posts ON posts rename to idx_posts_1#;
DROP TABLE IF EXISTS posts1;
CREATE TABLE posts1(post_id CHAR(2) NOT NULL, post_name CHAR(6) PRIMARY KEY, basic_wage INT,basic_bonus INT);
CREATE INDEX idx_posts ON posts1(post_id ASC, post_name);
ALTER INDEX idx_posts_1# ON posts rename to idx_posts;
conn / as sysdba
drop user a cascade;

--DTS2019041104120
DROP TABLE IF EXISTS RENAME_IND_CON_17;
CREATE TABLE RENAME_IND_CON_17(c1 int, c2 varchar(32), c3 bigint);
INSERT INTO RENAME_IND_CON_17 VALUES(50, 'P1', 5000);
INSERT INTO RENAME_IND_CON_17 VALUES(150, 'P2', 15000);
INSERT INTO RENAME_IND_CON_17 VALUES(250, 'P3', 25000);
INSERT INTO RENAME_IND_CON_17 VALUES(350, 'P4', 35000);
COMMIT;

ALTER TABLE RENAME_IND_CON_17 ADD CONSTRAINT pk_RENAME_IND_CON_17_1 unique(c1);
ALTER TABLE RENAME_IND_CON_17 ADD CONSTRAINT pk_RENAME_IND_CON_17_2 check(c3>2500);
ALTER TABLE RENAME_IND_CON_17 ADD CONSTRAINT pk_RENAME_IND_CON_17_3 PRIMARY KEY(c2);

ALTER TABLE RENAME_IND_CON_17 rename constraint pk_RENAME_IND_CON_17_1 to pk_RENAME_IND_CON_17_4;
ALTER TABLE RENAME_IND_CON_17 rename constraint pk_RENAME_IND_CON_17_2 to pk_RENAME_IND_CON_17_5;
ALTER TABLE RENAME_IND_CON_17 rename constraint pk_RENAME_IND_CON_17_3 to pk_RENAME_IND_CON_17_6;

ALTER TABLE RENAME_IND_CON_17 DROP CONSTRAINT pk_RENAME_IND_CON_17_4;
ALTER TABLE RENAME_IND_CON_17 DROP CONSTRAINT pk_RENAME_IND_CON_17_5;
ALTER TABLE RENAME_IND_CON_17 DROP CONSTRAINT pk_RENAME_IND_CON_17_6;

INSERT INTO RENAME_IND_CON_17 VALUES(250, 'P5', 4500);
INSERT INTO RENAME_IND_CON_17 VALUES(450, 'P6', 500);
INSERT INTO RENAME_IND_CON_17 VALUES(550, 'P3', 5000);

--DTS2019041001766
DROP TABLE IF EXISTS RENAME_IND_CON_4;
CREATE TABLE RENAME_IND_CON_4(c1 INTEGER,c2 INTEGER);
CREATE INDEX ix_RENAME_IND_4_1 ON RENAME_IND_CON_4(c1) initrans 255;
alter table RENAME_IND_CON_4 add constraint RENAME_CON_1 check(c1>1);
DROP TABLE IF EXISTS RENAME_IND_CON_5;
CREATE TABLE RENAME_IND_CON_5(c1 INTEGER,c2 INTEGER);
CREATE INDEX ix_RENAME_IND_5_1 ON RENAME_IND_CON_5(c1) initrans 255;
alter table RENAME_IND_CON_5 add constraint RENAME_CON_2 check(c1>1);
alter table RENAME_IND_CON_5 add constraint RENAME_CON_3 unique (c1);

alter  index ix_RENAME_IND_5_1 rename TO  ix_RENAME_IND_4_1;
alter table RENAME_IND_CON_5 rename constraint  RENAME_CON_2 to RENAME_CON_1;

select  t.name TB , i.name IDX  from SYS_TABLES t ,SYS_INDEXES i  where i.table#=t.id and t.name = 'RENAME_IND_CON_4';
select  t.name TB , i.name IDX  from SYS_TABLES t ,SYS_INDEXES i  where i.table#=t.id and t.name = 'RENAME_IND_CON_5';

--DTS2019041106652
DROP TABLE IF EXISTS posts;
CREATE TABLE posts(post_id CHAR(2) NOT NULL, post_name CHAR(6) PRIMARY KEY, basic_wage INT,basic_bonus INT);
CREATE INDEX idx_posts ON posts(post_id ASC, post_name);
CREATE INDEX idx_posts ON posts(basic_wage ASC, post_name); 

