DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS EMP1;
DROP TABLE IF EXISTS EMP_2;
DROP TABLE IF EXISTS EMP_3;
DROP TABLE IF EXISTS EMP_4;
DROP TABLE IF EXISTS EMP_6;

CREATE TABLE  EMP (EMPNO NUMBER(4) NOT NULL, ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER(7, 2),DEPTNO NUMBER(2));
INSERT INTO EMP VALUES (1, 'SMITH', 'CLERK',     800,    20);
INSERT INTO EMP VALUES (2, 'ALLEN', 'SALESMAN', 1600,    30);
INSERT INTO EMP VALUES (3, 'WARD',  'SALESMAN', 1250,    30);
INSERT INTO EMP VALUES (4, 'JONES', 'MANAGER',  2975,    20);
INSERT INTO EMP VALUES (5, 'MARTIN','SALESMAN', 1250,    30);
INSERT INTO EMP VALUES (6, 'BLAKE', 'MANAGER',  2850,    30);
INSERT INTO EMP VALUES (7, 'CLARK', 'MANAGER',  2850,    10);
INSERT INTO EMP VALUES (8, 'SCOTT', 'ANALYST',  3000,    20);
INSERT INTO EMP VALUES (9, 'KING',  'PRESIDENT',3000,    10);
INSERT INTO EMP VALUES (10,'TURNER','SALESMAN', 1500,    30);
INSERT INTO EMP VALUES (11,'ADAMS', 'CLERK',    1500,    20);

CREATE TABLE  EMP1 (EMPNO NUMBER(4) NOT NULL, ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER(7, 2),DEPTNO NUMBER(2));
INSERT INTO EMP1 VALUES (1, 'SMITH', 'CLERK',     800,    20);

CREATE TABLE  EMP_2 (EMPNO NUMBER(4) NOT NULL, ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER(7, 2),DEPTNO NUMBER(2));
INSERT INTO EMP_2 VALUES (9, 'KING',  'PRESIDENT',3000,    10);

CREATE TABLE  EMP_3 (EMPNO NUMBER(4) NOT NULL, ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER(10, 3),DEPTNO NUMBER(2));
INSERT INTO EMP_3 VALUES (21, 'BLAKE2', 'MANAGER',  1,    30);
INSERT INTO EMP_3 VALUES (20, 'BLAKE1', 'MANAGER',  999999,    30);

CREATE TABLE  EMP_4 (EMPNO NUMBER(4) NOT NULL, ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER(10, 3),DEPTNO NUMBER(2));
INSERT INTO EMP_4 VALUES (21, 'BLAKE2', 'MANAGER',  1000,    30);
INSERT INTO EMP_4 VALUES (20, 'BLAKE1', 'MANAGER',  9999,    30);
INSERT INTO EMP_4(EMPNO, ENAME, JOB, DEPTNO) VALUES (23, 'BLAKE3', 'MANAGER', 30);

CREATE TABLE  EMP_6 (EMPNO NUMBER(4) NOT NULL, ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER ,DEPTNO NUMBER(2));
INSERT INTO EMP_6 VALUES (1, 'SMITH', 'CLERK',     9.000E126,    30);
INSERT INTO EMP_6 VALUES (2, 'SMITH2', 'CLERK',     9.000E126,    30);
INSERT INTO EMP_6 VALUES (1, 'SMITH', 'CLERK',     9.000E70,    30);
INSERT INTO EMP_6 VALUES (2, 'SMITH2', 'CLERK',     9.000E70,    30);

DROP TABLE IF EXISTS RQG_LIST_DATATYPE_034;
CREATE TABLE RQG_LIST_DATATYPE_034(ID INT NOT NULL ,C_INT INT ,C_INTEGER INTEGER NOT NULL );
INSERT INTO RQG_LIST_DATATYPE_034 VALUES(1,11,111);
INSERT INTO RQG_LIST_DATATYPE_034 VALUES(2,22,222);
INSERT INTO RQG_LIST_DATATYPE_034 VALUES(3,33,333);

set numwidth 10;

select stddev(SAL) from EMP;
select stddev_samp(SAL) from EMP;
select stddev_pop(SAL) from EMP;

select stddev(SAL) from EMP1;
select stddev_samp(SAL) from EMP1;
select stddev_pop(SAL) from EMP1;

select stddev(SAL) from EMP_2;
select stddev_samp(SAL) from EMP_2;
select stddev_pop(SAL) from EMP_2;

select stddev(SAL), stddev_pop(SAL), stddev_samp(SAL) from EMP;
select stddev(SAL), stddev_pop(SAL) from EMP_3;
select stddev_pop(SAL)  from EMP_3;

select stddev(SAL) from EMP_4;
select stddev_samp(SAL) from EMP_4;
select stddev_pop(SAL) from EMP_4;

select stddev(C_INT) from RQG_LIST_DATATYPE_034;
select stddev_samp(C_INT) from RQG_LIST_DATATYPE_034;
select stddev_pop(C_INT) from RQG_LIST_DATATYPE_034;

SELECT EMPNO, ENAME, SAL, JOB, STDDEV(SAL) OVER (ORDER BY JOB) "StdDev" FROM EMP;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV(SAL) OVER (PARTITION BY JOB ORDER BY ENAME) "StdDev1" FROM EMP WHERE DEPTNO = 30;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV(SAL) OVER (PARTITION BY JOB ORDER BY ENAME) "StdDev2" FROM EMP;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV_POP(SAL) OVER (ORDER BY JOB) "StdDev_POP" FROM EMP;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV_SAMP(SAL) OVER (ORDER BY JOB) "StdDev_SAMP" FROM EMP;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV_POP(SAL) OVER (ORDER BY JOB) "StdDev_POP4" FROM EMP_4;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV(SAL) OVER (ORDER BY JOB) "StdDev_4" FROM EMP_4;
SELECT EMPNO, ENAME, SAL, JOB, STDDEV_SAMP(SAL) OVER (ORDER BY JOB) "StdDev_SMP4" FROM EMP_4;

SELECT EMPNO, ENAME, SAL, JOB, STDDEV(ENAME) OVER (ORDER BY JOB) "StdDev" FROM EMP;
SELECT ENAME, SAL, JOB, STDDEV(SAL) OVER (ORDER BY JOB) "StdDev6" FROM EMP_6;

DROP TABLE EMP;
DROP TABLE EMP1;
DROP TABLE EMP_2;
DROP TABLE EMP_3;
DROP TABLE EMP_4;
DROP TABLE EMP_6;
DROP TABLE RQG_LIST_DATATYPE_034;
