conn / as  sysdba 
drop sequence if exists seq_0011;
drop sequence if exists seq_0012;
create sequence seq_0012 increment by -9223372036854775808 start with 0 maxvalue 9223372036854775807 minvalue -9223372036854775808 NOCACHE ;
create sequence seq_0011 increment by -9 start with 0 maxvalue 9223372036854775807 minvalue -10 NOCACHE;
alter sequence seq_0011 increment by -9223372036854775808  maxvalue 9223372036854775807 minvalue -9223372036854775808 NOCACHE ;
drop sequence if exists seq_0011;
drop sequence if exists seq_0012;
CONN / AS SYSDBA
DROP SEQUENCE IF EXISTS QUE_TEST11;
CREATE SEQUENCE QUE_TEST11 INCREMENT BY -1 MAXVALUE -10 START WITH -15;
ALTER SEQUENCE QUE_TEST11 MAXVALUE -5;
DROP SEQUENCE IF EXISTS QUE_TEST11;
DROP USER IF EXISTS PRI_SEQUENCE;
CREATE USER PRI_SEQUENCE IDENTIFIED BY CANTIAN_234;
GRANT CONNECT, CREATE SEQUENCE TO PRI_SEQUENCE;
CONN PRI_SEQUENCE/CANTIAN_234@127.0.0.1:1611
CREATE SEQUENCE PRI_SEQUENCE1.QUE_TEST11 INCREMENT BY -1 MAXVALUE -10 START WITH -15;
ALTER SEQUENCE PRI_SEQUENCE1.QUE_TEST11 MAXVALUE -5;
CONN / AS SYSDBA
DROP USER IF EXISTS PRI_SEQUENCE;
CONN / AS SYSDBA 
DROP SEQUENCE IF EXISTS PFA_SEQ_TEST;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 1  INCREMENT BY 10 START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 START WITH 2 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MAXVALUE 1.0E8 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 10 MAXVALUE 1.0E9 MINVALUE 1 MINVALUE 10 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE NOCACHE NOCACHE ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 CACHE 30 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER NOORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER NOMAXVALUE NOMAXVALUE ;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 10  START WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER NOMINVALUE NOMINVALUE ;
-- invalid cases
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 1.123123 START    WITH 1 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 1.00 START WITH 1.0001 MAXVALUE 1.0E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 1.00 START WITH 1. MAXVALUE 1.000000000000000000000000001E9 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 1.00 START WITH 1. MAXVALUE 1.0000000E17 MINVALUE 0.002 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST  INCREMENT BY 1.00 START WITH 1. MAXVALUE 1.0000000E17 MINVALUE 2 NOCYCLE CACHE 0.0200001E2 ORDER;

-- normal case
drop sequence if exists PFA_SEQ_TEST_N;
CREATE  SEQUENCE PFA_SEQ_TEST_N  INCREMENT BY 1.00 START WITH 1.01E10 MAXVALUE 1.000000000000000000000000001E30 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE  SEQUENCE PFA_SEQ_TEST_N  INCREMENT BY 1.00 START WITH 1.01E10 MAXVALUE 1.000000000000000000000000001E30 MINVALUE 1 NOCYCLE CACHE 20 ORDER;

CREATE SEQUENCE  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB64 START WITH 10;
SELECT AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB64.NEXTVAL FROM DUAL;
DROP SEQUENCE  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB64;

--DTS2018070911143
drop sequence if exists slient_mode_seque_007;
CREATE SEQUENCE slient_mode_seque_007 START WITH 10 MAXVALUE 20 INCREMENT BY 1 CYCLE;
CREATE SEQUENCE slient_mode_seque_007 START WITH 10 MAXVALUE 20 INCREMENT BY 1 CYCLE CACHE 1;
CREATE SEQUENCE slient_mode_seque_007 START WITH 10 MAXVALUE 20 INCREMENT BY 1 CYCLE CACHE 19; 
drop sequence if exists slient_mode_seque_008;
CREATE SEQUENCE slient_mode_seque_008 START WITH 10 MAXVALUE 20 INCREMENT BY 3 CYCLE CACHE 7;
CREATE SEQUENCE slient_mode_seque_008 START WITH 10 MAXVALUE 20 INCREMENT BY 3 CYCLE CACHE 8; 
drop sequence slient_mode_seque_007;
drop sequence slient_mode_seque_008;

-- CREATE SEQUENCE 
-- ����CURRVAL 
DROP SEQUENCE if exists seq1;
DROP SEQUENCE if exists seq2;

CREATE SEQUENCE seq1 INCREMENT BY 1  NOCACHE NOCYCLE;        
select SEQ1.CURRVAL FROM DUAL;    
select SEQ1.NEXTVAL FROM DUAL;   
select SEQ1.CURRVAL FROM DUAL; 
select SEQ1.NEXTVAL FROM DUAL; 
select SEQ1.CURRVAL FROM DUAL;
rollback;
select SEQ1.CURRVAL FROM DUAL;
drop sequence seq1;

-- ����ָ��ֵ�����Χ 
CREATE SEQUENCE seq1  MAXVALUE 999999999999999999 INCREMENT BY 1  NOCACHE NOCYCLE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
DROP SEQUENCE SEQ1;
CREATE SEQUENCE seq1  MAXVALUE 1000000000000000000 INCREMENT BY 1  NOCACHE NOCYCLE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
DROP SEQUENCE SEQ1; 

-- ����ָ��ֵ����С��Χ
CREATE SEQUENCE seq1  MINVALUE -999999999999999999 INCREMENT BY 1  NOCACHE NOCYCLE;    
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
DROP sequence seq1;
CREATE SEQUENCE seq1  MINVALUE -1000000000000000000 INCREMENT BY 1  NOCACHE NOCYCLE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
DROP sequence seq1;
-- ����Ĭ��ֵ
CREATE SEQUENCE seq1;    
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER, FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

-- ���Ը�ֵ����
CREATE SEQUENCE seq1  START WITH -3 INCREMENT BY -1; 
select SEQ1.CURRVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ;   
select SEQ1.NEXTVAL  FROM DUAL ;  
drop sequence seq1;

-- ����NOCYCLE������MAXVALUEʱ
CREATE SEQUENCE seq1  START WITH 4 MAXVALUE 10 INCREMENT BY  3 NOCYCLE;
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
drop sequence seq1;

-- ����NOCYCLE������MINVALUEʱ
CREATE SEQUENCE seq1  MINVALUE -10 INCREMENT BY -4 NOCYCLE;
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ;
select SEQ1.NEXTVAL  FROM DUAL ;  
drop sequence seq1;

-- ���Բ���ֵ�����Χ��Ĭ����NOCYCLE
CREATE SEQUENCE seq1  START WITH 10 MAXVALUE 20 INCREMENT BY 4 CYCLE;
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ;
drop sequence seq1;

CREATE SEQUENCE seq1 MINVALUE -10 INCREMENT BY -5 CYCLE;
select SEQ1.NEXTVAL  FROM DUAL ;
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ; 
select SEQ1.NEXTVAL  FROM DUAL ;
drop sequence seq1;

-- ���Է�����
CREATE SEQUENCE seq1  INCREMENT BY 8.8;
CREATE SEQUENCE seq1  MAXVALUE 888.88; 
CREATE SEQUENCE seq1  MINVALUE -888.88; 
CREATE SEQUENCE seq1  CACHE 8.8;      
CREATE SEQUENCE seq1  START WITH 8.8;

-- ���� INCREMENT �� MAX-MIN�й�
CREATE SEQUENCE seq1  INCREMENT BY 0;
CREATE SEQUENCE seq1  MAXVALUE 30 MINVALUE 2 INCREMENT BY  30;


-- ����START WITH �� MAX MIN�й�
CREATE SEQUENCE seq1 START WITH 12; 
select SEQ1.NEXTVAL  FROM DUAL ;  
select SEQ1.NEXTVAL  FROM DUAL ;  
drop sequence seq1;
CREATE SEQUENCE seq1 START WITH 5  MAXVALUE 9 ; 
drop sequence seq1;
CREATE SEQUENCE seq1 START WITH -10 MINVALUE 9 INCREMENT BY -1; 

-- NOMAXVALUE
CREATE SEQUENCE seq1  NOMAXVALUE  INCREMENT BY 20;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

CREATE SEQUENCE seq1  NOMAXVALUE  INCREMENT BY -10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

CREATE SEQUENCE seq1  NOMAXVALUE  INCREMENT BY 20  CYCLE;
CREATE SEQUENCE seq1  NOMINVALUE  INCREMENT BY -10 CYCLE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

-- NOMINVALUE �� CYCLE �й�
CREATE SEQUENCE seq1  NOMINVALUE INCREMENT BY 10;
select SEQ1.NEXTVAL  FROM DUAL ;
drop sequence seq1;

CREATE SEQUENCE seq1  NOMINVALUE INCREMENT BY -10;
select SEQ1.NEXTVAL  FROM DUAL ;
drop sequence seq1;

CREATE SEQUENCE seq1  NOMINVALUE INCREMENT BY -10  CYCLE;

CREATE SEQUENCE seq1  NOMINVALUE INCREMENT BY 10 CYCLE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

-- CACHE size test
CREATE SEQUENCE seq1 ; 
SELECT NAME, CACHESIZE, CYCLE_FLAG  FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

CREATE SEQUENCE seq1  CACHE 128;
drop sequence seq1;

CREATE SEQUENCE seq1  CACHE 999999999999999999;
SELECT NAME, CACHESIZE, CYCLE_FLAG  FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

create sequence seq4 start with 3000000001 cache 18446744073709551616;
create sequence seq4 start with 3000000001 cache 9999999999999999999;

-- OK too 
CREATE SEQUENCE seq2  CACHE 1000000000000000000;
SELECT NAME, CACHESIZE, CYCLE_FLAG  FROM SYS_SEQUENCES WHERE NAME = 'SEQ2';
drop sequence seq2;

CREATE SEQUENCE seq1 CACHE 0;
drop sequence seq1;

CREATE SEQUENCE seq1 CACHE -1;

CREATE SEQUENCE seq1 CACHE -9223372036854775807;

--(CEIL (MAXVALUE - MINVALUE)) / ABS (INCREMENT)
CREATE SEQUENCE seq1  MINVALUE  100  MAXVALUE 990 INCREMENT BY 13 CACHE 70 CYCLE; 
CREATE SEQUENCE seq1  MINVALUE  100  MAXVALUE 990 INCREMENT BY 13 CACHE 69 CYCLE; 
CREATE SEQUENCE seq1  MINVALUE  100  MAXVALUE 990 INCREMENT BY 13 CACHE 68; 
drop sequence seq1;

-- ORDER
CREATE SEQUENCE seq1 NOCACHE NOORDER;
drop sequence seq1;
CREATE SEQUENCE seq1 NOCACHE ORDER;
drop sequence seq1;

-- ALTER SEQUENCE
CREATE SEQUENCE seq1;
ALTER SEQUENCE seq2;
ALTER SEQUENCE seq1;  
ALTER SEQUENCE seq2 NOMINVALUE; 

-- �޸�START WITH
ALTER SEQUENCE seq1 START WITH 2; 

-- �޸� INCREMENT
ALTER SEQUENCE seq1 INCREMENT BY -2;
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
select SEQ1.NEXTVAL  FROM DUAL ;
drop sequence seq1;
create sequence seq1 ;
select seq1.nextval from dual;
alter sequence seq1 increment by 2;
select name , Last_number from SYS_SEQUENCES where name ='SEQ1';
alter sequence seq1 cache 30;
select name , Last_number from SYS_SEQUENCES where name ='SEQ1';
alter sequence seq1 cache 40 increment by 3;
select name , Last_number from SYS_SEQUENCES where name ='SEQ1';
select seq1.nextval from dual;
select name , Last_number from SYS_SEQUENCES where name ='SEQ1';

ALTER SEQUENCE seq1  START WITH 10 MAXVALUE 40 INCREMENT BY 1 CYCLE;
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
select SEQ1.NEXTVAL  FROM DUAL ;
drop sequence seq1;

-- �޸�MAXVALUE
CREATE SEQUENCE seq1 ;
ALTER SEQUENCE seq1 MAXVALUE  1000;
ALTER SEQUENCE seq1 INCREMENT BY 20;
select SEQ1.NEXTVAL  FROM DUAL ;
select SEQ1.NEXTVAL  FROM DUAL ;
 
ALTER SEQUENCE seq1 MAXVALUE  200;
ALTER SEQUENCE seq1 MAXVALUE  30;

ALTER SEQUENCE seq1 NOMAXVALUE;

-- �޸�MINVALUE
ALTER SEQUENCE seq1 MAXVALUE  -1000;
ALTER SEQUENCE seq1 INCREMENT BY -10;
select SEQ1.NEXTVAL  FROM DUAL ;
select SEQ1.NEXTVAL  FROM DUAL ;

ALTER SEQUENCE seq1 MINVALUE  200;
ALTER SEQUENCE seq1 MINVALUE  -30;
ALTER SEQUENCE seq1 NOMINVALUE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
drop sequence seq1;

-- ����CYCLE
CREATE sequence seq1;
ALTER SEQUENCE seq1 MINVALUE 1 MAXVALUE 10;
ALTER SEQUENCE seq1 CYCLE;
ALTER SEQUENCE seq1 MINVALUE 1 MAXVALUE 100 CYCLE;

ALTER SEQUENCE seq1 CACHE 10;
ALTER SEQUENCE seq1 CACHE 100;

ALTER SEQUENCE seq1 ORDER;
ALTER SEQUENCE seq1 NOORDER;

DROP SEQUENCE seq1;

-- ����LASTNUMBER 
CREATE SEQUENCE seq1 MAXVALUE 40 INCREMENT BY 1 NOCYCLE NOCACHE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 MAXVALUE 50 INCREMENT BY 1 CYCLE;        
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 MAXVALUE 60 CYCLE CACHE 20; 
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY 12 NOCYCLE;
ALTER SEQUENCE seq1 MAXVALUE 100 INCREMENT BY 12 CACHE 10 NOCYCLE; 
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1'; 
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY -12 NOCYCLE;					
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

DROP SEQUENCE seq1;
-----------

CREATE SEQUENCE seq1 MAXVALUE 30 INCREMENT BY 2 NOCYCLE CACHE 10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;    
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 MAXVALUE 30 INCREMENT BY 1 CYCLE;     
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY 1 CYCLE NOCACHE; 
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1'; 

ALTER SEQUENCE seq1 INCREMENT BY 10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY -10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
DROP SEQUENCE seq1;

CREATE SEQUENCE seq1 START WITH 18 MAXVALUE 20 INCREMENT BY 1 NOCYCLE CACHE 10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1'; 
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
DROP SEQUENCE seq1;
---------------
CREATE SEQUENCE seq1 MAXVALUE 20 INCREMENT BY 1 CYCLE NOCACHE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1'; 


ALTER SEQUENCE seq1 MAXVALUE 200 INCREMENT BY 1 CYCLE CACHE 30; 
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY 2;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY -2;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
DROP SEQUENCE seq1;

CREATE SEQUENCE seq1 MAXVALUE 30 INCREMENT BY 1 CYCLE CACHE 8;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';
select SEQ1.NEXTVAL  FROM DUAL ;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY 1 NOCYCLE;  
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY 1 NOCACHE;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY 10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 INCREMENT BY -10;
SELECT NAME, MINVAL, MAXVAL, STEP, CACHESIZE, CYCLE_FLAG, ORDER_FLAG, LAST_NUMBER FROM SYS_SEQUENCES WHERE NAME = 'SEQ1';

ALTER SEQUENCE seq1 CACHE 18446744073709551616;

DROP SEQUENCE seq1;

-- ����SCHEMA�µ�����
CREATE USER SEQ_TEST IDENTIFIED BY Root123456789;
CREATE SEQUENCE SEQ_TEST.seq1 MAXVALUE 30 INCREMENT BY 2 CYCLE CACHE 9;
select SEQ_TEST.SEQ1.NEXTVAL FROM DUAL;
select SEQ_TEST.SEQ1.CURRVAL FROM DUAL;
ALTER SEQUENCE SEQ_TEST.seq1 INCREMENT BY  3;

select sEq_teSt.Seq1.NEXTVAL FROM DUAL; 
select SeQ_TeST.SeQ1.CURRVAL FROM DUAL;

select sEq_teSt.Seq1.NEXTVAL FROM DUAL;
select sEq_teSt.Seq1.CURRVAL FROM DUAL;

DROP SEQUENCE SEQ_TEST.seq1;
drop sequence if exists SEQ_TEST.seq2;
DROP USER SEQ_TEST;
-- seq3 not exists
drop sequence if exists seq3;

CREATE SEQUENCE seq1  MAXVALUE 999999999999999999 MINVALUE -999999999999999999  START WITH 999999999999999996 INCREMENT BY 999999999999999990  CACHE 999999999999999995 NOCYCLE;
drop sequence seq1;

-- test overflow 
CREATE SEQUENCE seq1  MAXVALUE 999999999999999999 MINVALUE -999999999999999999  START WITH 999999999999999996 INCREMENT BY -999999999999999990  CACHE 999999999999999995 NOCYCLE;
CREATE SEQUENCE seq1  MAXVALUE 999999999999999999 MINVALUE -999999999999999999  START WITH 999999999999999996 INCREMENT BY -999999999999999990  NOCACHE NOCYCLE;
select SEQ1.NEXTVAL  FROM DUAL;
select SEQ1.NEXTVAL  FROM DUAL;
select SEQ1.NEXTVAL  FROM DUAL;
select SEQ1.NEXTVAL  FROM DUAL;
drop sequence seq1;
 
CREATE SEQUENCE seq1  MAXVALUE 999999999999999999 MINVALUE -999999999999999999  START WITH 999999999999999990 INCREMENT BY 999999999999999990  NOCACHE NOCYCLE;
select SEQ1.NEXTVAL  FROM DUAL;
select SEQ1.NEXTVAL  FROM DUAL;
drop sequence seq1;

CREATE SEQUENCE SEQUENCE ;
select SEQUENCE.NEXTVAL FROM DUAL;
select sequence.NEXTVAL FROM DUAL;
select sequence.CURRVAL FROM DUAL;
drop sequence SEQUENCE;

-- DTS2018072011785
drop sequence if exists seq_t_view_dspresc;
create sequence seq_t_view_dspresc
minvalue 9223372036854775806
maxvalue 99999999999999999999
start with 9223372036854775806
increment by 1
cache 20
cycle
order;

drop sequence if exists seq_t_view_dspresc;
create sequence seq_t_view_dspresc
minvalue -9223372036854775807
maxvalue 99999999999999999999
start with -9223372036854775807
increment by 1
cache 20;
DROP SEQUENCE IF EXISTS TEST_PART_SEQ;
CREATE SEQUENCE TEST_PART_SEQ INCREMENT BY 1  NOCACHE NOCYCLE;
DROP TABLE IF EXISTS TEST_PART_SEQ_T1;
CREATE TABLE TEST_PART_SEQ_T1(F1 INT, F2 INT, F3 INT)
PARTITION BY RANGE(F1)
(
 PARTITION P1 VALUES LESS THAN(10),
 PARTITION P4 VALUES LESS THAN(MAXVALUE)
);
INSERT INTO TEST_PART_SEQ_T1 VALUES(TEST_PART_SEQ.NEXTVAL,10,10);
INSERT INTO TEST_PART_SEQ_T1 VALUES(TEST_PART_SEQ.NEXTVAL,20,20);
SELECT * FROM TEST_PART_SEQ_T1 ORDER BY F1;
DROP SEQUENCE IF EXISTS TEST_PART_SEQ;
DROP TABLE IF EXISTS TEST_PART_SEQ_T1;

DROP SEQUENCE IF EXISTS TEST_SEQ_1;
CREATE SEQUENCE TEST_SEQ_1 START WITH 1 MINVALUE 1 MAXVALUE 99999999999999999999;
DROP TABLE IF EXISTS TEST_SEQ_T1;
CREATE TABLE TEST_SEQ_T1(F1 INT, F2 INT, F3 INT);
SELECT TEST_SEQ_1.nextval, TEST_SEQ_1.nextval, TEST_SEQ_1.currval from dual;
SELECT TEST_SEQ_1.currval, TEST_SEQ_1.nextval, TEST_SEQ_1.currval from dual;
insert into TEST_SEQ_T1 values(TEST_SEQ_1.nextval,TEST_SEQ_1.nextval,TEST_SEQ_1.nextval);
select * from TEST_SEQ_T1;
commit;

DROP TABLE IF EXISTS TEST_SEQ_T1;
DROP SEQUENCE IF EXISTS TEST_SEQ_1;

drop sequence if exists s_sequence_00025;
create sequence s_sequence_00025 increment by 10;

drop table if exists t_sysdate_systimestamp_base;
create table t_sysdate_systimestamp_base(id int);
insert into t_sysdate_systimestamp_base values(1);
insert into t_sysdate_systimestamp_base values(4);
commit;

drop table if exists t_sequence_00025;
create table t_sequence_00025(id int,
c1 int default s_sequence_00025.nextval,
c2 int default s_sequence_00025.nextval,
c3 int default s_sequence_00025.currval,
c4 int default s_sequence_00025.currval);

insert into t_sequence_00025(id) select * from t_sysdate_systimestamp_base;
select * from t_sequence_00025 order by 1;
drop table t_sequence_00025;
drop table t_sysdate_systimestamp_base;

drop sequence if exists s_sequence_00018;
drop table if exists t_sequence_00018;
create sequence s_sequence_00018 increment by 10;
create table t_sequence_00018 as select s_sequence_00018.nextval c1,s_sequence_00018.currval c2,s_sequence_00018.nextval c3,s_sequence_00018.currval c4 from dual;
select * from t_sequence_00018;
select s_sequence_00018.currval c1,s_sequence_00018.nextval c2,s_sequence_00018.currval c3,s_sequence_00018.nextval c4 from dual;
drop table t_sequence_00018;
drop sequence s_sequence_00018;

drop table if exists seq_check;
create table seq_check(val int);

declare
i int;
begin
	for i in 1 ..2100
	loop
	execute immediate 'create sequence seq_'||i||' start with '||i||'';
	end loop;
end;
/

declare
i int;
begin
	for i in 1 ..2100
	loop
	execute immediate 'insert into seq_check values(seq_'||i||'.nextval)';
	end loop;
	commit;
end;
/

declare
i int;
begin
	for i in 1 ..2100
	loop
	execute immediate 'drop sequence seq_'||i||'';
	end loop;
	for i in 3000 ..3100
	loop
	execute immediate 'create sequence seq_'||i||' start with '||i||'';
	end loop;
end;
/

declare
i int;
begin	
	for i in 3000 ..3100
	loop
	execute immediate 'insert into seq_check values(seq_'||i||'.nextval)';
	end loop;
	commit;
	for i in 3000 ..3100
	loop
	execute immediate 'drop sequence seq_'||i||'';
	end loop;
end;
/

select sum(val) from seq_check;
drop table seq_check;

--DTS2019013000524  drop seq error
drop user if exists nebula cascade;
create sequence nebula.strg_indx_coalesce_tbl_002_seq;

--DTS2019082907255   core
drop table if exists tbl_base;
create table tbl_base(id int not null,c_bigint bigint);
DROP SEQUENCE IF EXISTS seq_001;
create sequence seq_001 start with 1 increment by 1 MAXVALUE 40000000 MINVALUE -40000000 NOCYCLE distribute by groupid(1,2,3);
create sequence seq_001 start with 1 increment by 1 MAXVALUE 40000000 MINVALUE -40000000 NOCYCLE;
insert into tbl_base values ( 0,seq_001.nextval);
insert into tbl_base values ( 1,seq_001.nextval);
insert into tbl_base values ( 2,seq_001.nextval);
insert into tbl_base values ( 3,seq_001.nextval);
insert into tbl_base values ( 4,seq_001.nextval);
insert into tbl_base values ( 5,seq_001.nextval);

commit;
select id,c_bigint from tbl_base order by id limit seq_001.nextval-9000 offset seq_001.nextval;

--DTS2019090205460
drop SEQUENCE ADDZCL_TEST11;
CREATE SEQUENCE ADDZCL_TEST11 START WITH 1 INCREMENT BY 3 MINVALUE 1 MAXVALUE 100 CYCLE CACHE 10;
ALTER SEQUENCE ADDZCL_TEST11 INCREMENT BY 3 MINVALUE 1 NOMAXVALUE CYCLE CACHE 10;
ALTER SEQUENCE ADDZCL_TEST11 INCREMENT BY 3 MINVALUE 1 NOMAXVALUE CYCLE;
ALTER SEQUENCE ADDZCL_TEST11 INCREMENT BY -3 NOMINVALUE MAXVALUE 30 CYCLE;
drop SEQUENCE ADDZCL_TEST11;
--DTS2019082909787 sequence error
drop sequence seq4;
drop table if exists tbv_base;
create table tbv_base(id int not null,c_bigint number(38));
DROP SEQUENCE IF EXISTS seq_9787;
create sequence seq_9787 increment by 2 start with 1 maxvalue 80000 nocycle;
insert into tbv_base values ( 0,seq_9787.nextval );
insert into tbv_base values ( 1,seq_9787.nextval);
insert into tbv_base values ( 2,seq_9787.nextval);
insert into tbv_base values ( 3,seq_9787.nextval);
insert into tbv_base values ( 4,seq_9787.nextval);
insert into tbv_base values ( 5,seq_9787.nextval);
create or replace view view_sequence_9787 as select seq_9787.nextval as c1 from tbv_base;

drop sequence if exists seq1;
create sequence seq1;
alter sequence seq1 nomaxvalue maxvalue 100;
alter sequence seq1 nominvalue minvalue 1;
alter sequence seq1 nocache cache 100;

drop table if exists t_count_base_001;
create table t_count_base_001(id int,deptno int,name varchar(20),sal int);
insert into t_count_base_001 values(1,1,'1aa',120);
insert into t_count_base_001 values(2,1,'2aa',300);
insert into t_count_base_001 values(3,1,'3aa',100);
insert into t_count_base_001 values(4,1,'4aa',99);
insert into t_count_base_001 values(5,1,'5aa',90);
DROP SEQUENCE if exists seq_auto_extend; 
CREATE SEQUENCE seq_auto_extend START WITH 10 MAXVALUE 200 INCREMENT BY 2 CYCLE;
--this three nort supprt 
select count(distinct id) over(partition by seq_auto_extend.nextval) from t_count_base_001 where id<5;
select count(distinct seq_auto_extend.nextval) over() from t_count_base_001 where id<5;
select count(distinct seq_auto_extend.nextval) over(partition by seq_auto_extend.nextval) from t_count_base_001 where id<5;
--support
select id, seq_auto_extend.nextval, count(distinct id) over() from t_count_base_001 where id<5 order by 1;

--DTS2019102300607
drop sequence if exists sxj_seq_001;
create sequence sxj_seq_001 increment by -9223372036854775807 start with 0 maxvalue 9223372036854775807 minvalue -9223372036854775807;
select sxj_seq_001.nextval from dual;
select sxj_seq_001.nextval from dual;
select sxj_seq_001.nextval from dual;

--DTS2019120615580
drop sequence if exists XXX0;
CREATE SEQUENCE XXX0 INCREMENT BY 5 START WITH 0 MAXVALUE 10 MINVALUE 0 CYCLE  NOCACHE;
SELECT XXX0.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX0';
SELECT XXX0.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX0';
SELECT XXX0.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX0';
SELECT XXX0.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX0';
SELECT XXX0.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX0';
SELECT XXX0.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX0';
drop sequence XXX0;

drop sequence if exists XXX1;
CREATE SEQUENCE XXX1 INCREMENT BY 4 START WITH 0 MAXVALUE 5 MINVALUE -5 CYCLE  CACHE 2;
SELECT XXX1.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX1';
SELECT XXX1.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX1';
SELECT XXX1.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX1';
SELECT XXX1.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX1';
SELECT XXX1.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX1';
SELECT XXX1.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX1';
drop sequence XXX1;

drop sequence if exists XXX2;
CREATE SEQUENCE XXX2 INCREMENT BY -5 START WITH 0 MAXVALUE 10 MINVALUE -10 CYCLE NOCACHE;
SELECT XXX2.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX2';
SELECT XXX2.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX2';
SELECT XXX2.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX2';
SELECT XXX2.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX2';
SELECT XXX2.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX2';
SELECT XXX2.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX2';
drop sequence XXX2;

drop sequence if exists XXX3;
CREATE SEQUENCE XXX3 INCREMENT BY -5 START WITH 0 MAXVALUE 10 MINVALUE -10 CYCLE CACHE 2;
SELECT XXX3.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX3';
SELECT XXX3.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX3';
SELECT XXX3.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX3';
SELECT XXX3.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX3';
SELECT XXX3.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX3';
SELECT XXX3.NEXTVAL FROM DUAL; 
SELECT last_number FROM all_sequences WHERE SEQUENCE_NAME='XXX3';
drop sequence XXX3;


--test single sql for seq soft parse
drop sequence if exists seq_soft_parse;
create sequence seq_soft_parse;
select seq_soft_parse.nextval from sys_dummy;
drop table if exists tab_seq_save_parse_time;
create table tab_seq_save_parse_time as select PARSE_TIME as save_time from dv_sqls where sql_text like 'select seq_soft_parse.nextval%' and valid=1;
select seq_soft_parse.nextval from sys_dummy;
select parse_calls, PARSE_TIME-(select save_time from tab_seq_save_parse_time) from dv_sqls where sql_text like 'select seq_soft_parse.nextval%' and valid=1;

--test anonymous for seq soft parse
drop sequence if exists seq_soft_parse_anon;
create sequence seq_soft_parse_anon;

declare
tmp1 int;
begin
select seq_soft_parse_anon.nextval into tmp1 from sys_dummy;
end;
/

declare
tmp2 int;
begin
select seq_soft_parse_anon.nextval into tmp2 from sys_dummy;
end;
/

declare
tmp1 int;
begin
select seq_soft_parse_anon.nextval into tmp1 from sys_dummy;
end;
/
select parse_calls,valid from dv_sqls where sql_text like 'select seq_soft_parse_anon.nextval%' order by 1,2;
select parse_calls,valid from DV_ANONYMOUS where sql_text like '%seq_soft_parse_anon.nextval%' order by 1,2;